// lib/frasesData.ts

export interface Frase {
  texto: string;
  tags: string[];
}

export const frases: Frase[] = [
  // PAZ (25 frases)
  { texto: "Você é mais forte do que imagina e mais amado do que pode compreender.", tags: ["paz"] },
  { texto: "Cada novo dia é uma oportunidade de recomeçar com esperança renovada.", tags: ["paz"] },
  { texto: "A calma que você busca já existe dentro de você, apenas espera ser descoberta.", tags: ["paz"] },
  { texto: "Respire fundo: você já superou dias difíceis antes e superará este também.", tags: ["paz"] },
  { texto: "Sua jornada é única e valiosa, não compare seu capítulo 3 com o capítulo 20 de alguém.", tags: ["paz"] },
  { texto: "Pequenos progressos ainda são progressos. Celebre cada passo dado.", tags: ["paz"] },
  { texto: "Você tem em si uma luz capaz de iluminar até os dias mais escuros.", tags: ["paz"] },
  { texto: "Confie no processo: as melhores flores crescem após as tempestades.", tags: ["paz"] },
  { texto: "Sua presença faz diferença no mundo, mesmo quando você não percebe.", tags: ["paz"] },
  { texto: "Não há pressa no crescimento da alma. Seja paciente consigo mesmo.", tags: ["paz"] },
  { texto: "Você foi criado para momentos como este: seja corajoso e siga em frente.", tags: ["paz"] },
  { texto: "A serenidade não é ausência de tempestade, mas paz em meio a ela.", tags: ["paz"] },
  { texto: "Cada desafio superado te torna mais sábio e resiliente para o próximo.", tags: ["paz"] },
  { texto: "Sua história ainda está sendo escrita, e os melhores capítulos estão por vir.", tags: ["paz"] },
  { texto: "Acredite em si: você tem tudo o que precisa para alcançar seus sonhos.", tags: ["paz"] },
  { texto: "A gratidão transforma o que temos em suficiente e mais do que suficiente.", tags: ["paz"] },
  { texto: "Escolha ser gentil consigo mesmo hoje, você merece compaixão e cuidado.", tags: ["paz"] },
  { texto: "Sua sensibilidade não é fraqueza, é um presente que torna o mundo melhor.", tags: ["paz"] },
  { texto: "O que te machucou no passado não define quem você é ou será no futuro.", tags: ["paz"] },
  { texto: "Você é digno de amor, alegria e todas as coisas boas da vida.", tags: ["paz"] },
  { texto: "A paz interior é seu direito de nascença, reclame-a hoje.", tags: ["paz"] },
  { texto: "Em meio ao caos, você pode escolher ser o centro de calma.", tags: ["paz"] },
  { texto: "Sua mente merece descanso, seu coração merece tranquilidade.", tags: ["paz"] },
  { texto: "Encontre a quietude dentro de si e deixe que ela seja sua fortaleza.", tags: ["paz"] },
  { texto: "A paz verdadeira vem de aceitar que você é exatamente onde precisa estar.", tags: ["paz"] },

  // CONFIANÇA (25 frases)
  { texto: "Confie no processo: a vida está escrevendo uma história linda através de você.", tags: ["confiança"] },
  { texto: "Quando não conseguir ver o caminho, confie que seus passos são guiados por amor.", tags: ["confiança"] },
  { texto: "Sua confiança interior pode mover montanhas, mas primeiro ela precisa mover você.", tags: ["confiança"] },
  { texto: "Não tema o desconhecido, pois quem te ama completamente vai à sua frente.", tags: ["confiança"] },
  { texto: "Cada 'não' que você recebe está te direcionando para o 'sim' perfeito da vida.", tags: ["confiança"] },
  { texto: "Solte o controle e permita que mãos mais sábias guiem seu destino.", tags: ["confiança"] },
  { texto: "Você é mais corajoso do que acredita e mais protegido do que consegue ver.", tags: ["confiança"] },
  { texto: "Confie: mesmo no vale mais escuro, você não caminha sozinho.", tags: ["confiança"] },
  { texto: "Sua vida tem um propósito maior do que você pode imaginar neste momento.", tags: ["confiança"] },
  { texto: "Quando tudo parecer perdido, lembre-se: a vida é especialista em milagres.", tags: ["confiança"] },
  { texto: "A confiança cresce a cada passo de fé, mesmo quando você não vê o destino.", tags: ["confiança"] },
  { texto: "Descanse na certeza: você está exatamente onde precisa estar agora.", tags: ["confiança"] },
  { texto: "Sua segurança não está no que você controla, mas em quem te sustenta.", tags: ["confiança"] },
  { texto: "Cada tempestade que você enfrentou te preparou para algo maior.", tags: ["confiança"] },
  { texto: "Confie mais no plano perfeito da vida do que nos seus próprios medos.", tags: ["confiança"] },
  { texto: "Você foi criado para voar, não para viver preso às suas limitações.", tags: ["confiança"] },
  { texto: "Quando não souber o próximo passo, apenas confie e continue caminhando.", tags: ["confiança"] },
  { texto: "Sua história ainda está sendo escrita pelas mãos mais amorosas do universo.", tags: ["confiança"] },
  { texto: "A confiança é a certeza de que algo incrível está sendo preparado para você.", tags: ["confiança"] },
  { texto: "Entregue suas ansiedades e receba em troca uma paz que excede todo entendimento.", tags: ["confiança"] },
  { texto: "Sua confiança na vida é a chave que abre portas impossíveis.", tags: ["confiança"] },
  { texto: "Mesmo quando você não entende, pode confiar no coração de quem te ama.", tags: ["confiança"] },
  { texto: "A confiança transforma obstáculos em oportunidades de crescimento.", tags: ["confiança"] },
  { texto: "Você pode não ver toda a escada, mas pode dar o primeiro passo.", tags: ["confiança"] },
  { texto: "Confie: o que a vida começa em você, ela completa com perfeição.", tags: ["confiança"] },

  // AMOR (25 frases)
  { texto: "Você é profundamente amado exatamente como é, não precisa se esforçar para merecer.", tags: ["amor"] },
  { texto: "O amor que você dá volta multiplicado para sua vida de formas inesperadas.", tags: ["amor"] },
  { texto: "Sua capacidade de amar é seu superpoder mais precioso no mundo.", tags: ["amor"] },
  { texto: "Não há força no universo mais poderosa que um coração que escolhe amar.", tags: ["amor"] },
  { texto: "Você foi criado no amor, pelo amor e para espalhar amor por onde passar.", tags: ["amor"] },
  { texto: "O amor verdadeiro sempre encontra um jeito de florescer, mesmo no deserto.", tags: ["amor"] },
  { texto: "Cada pessoa que cruza seu caminho é uma oportunidade de praticar o amor.", tags: ["amor"] },
  { texto: "Seu coração tem capacidade infinita de amar, não deixe que nada o endureça.", tags: ["amor"] },
  { texto: "O maior ato de coragem é amar sem medo de ser ferido novamente.", tags: ["amor"] },
  { texto: "Você merece um amor que celebre sua alma e encoraje seus sonhos.", tags: ["amor"] },
  { texto: "O amor que você busca fora já vive dentro do seu coração.", tags: ["amor"] },
  { texto: "Seja gentil: todos estão lutando batalhas que você não consegue ver.", tags: ["amor"] },
  { texto: "Um coração amoroso nunca envelhece e sempre encontra razões para sorrir.", tags: ["amor"] },
  { texto: "O amor é a única riqueza que aumenta quando você a compartilha.", tags: ["amor"] },
  { texto: "Escolha amar hoje, mesmo que o mundo te dê razões para fazer o contrário.", tags: ["amor"] },
  { texto: "Seu amor tem o poder de curar feridas que nem você conhece.", tags: ["amor"] },
  { texto: "No final, apenas o amor que você deu e recebeu realmente importará.", tags: ["amor"] },
  { texto: "Você é uma carta de amor de Deus para este mundo necessitado.", tags: ["amor"] },
  { texto: "O amor não é um sentimento apenas, é uma decisão que você toma todos os dias.", tags: ["amor"] },
  { texto: "Permita-se ser amado na mesma medida em que você ama os outros.", tags: ["amor"] },
  { texto: "O amor próprio não é egoísmo, é a base para amar outros de forma saudável.", tags: ["amor"] },
  { texto: "Cada ato de amor, por menor que seja, planta sementes de esperança no mundo.", tags: ["amor"] },
  { texto: "Você tem um coração feito para amar grandemente, não se contente com menos.", tags: ["amor"] },
  { texto: "O amor verdadeiro vê o melhor nas pessoas e as inspira a se tornarem isso.", tags: ["amor"] },
  { texto: "Sua maior contribuição ao mundo pode ser simplesmente amar sem reservas.", tags: ["amor"] },

  // FÉ (25 frases)
  { texto: "Sua fé é maior que seus medos, deixe que ela guie suas decisões.", tags: ["fé"] },
  { texto: "A fé não elimina as dúvidas, mas caminha com coragem através delas.", tags: ["fé"] },
  { texto: "Cada passo de fé que você dá fortalece sua confiança para o próximo.", tags: ["fé"] },
  { texto: "Sua fé é como uma semente: pequena no início, mas com potencial infinito.", tags: ["fé"] },
  { texto: "Não importa quão fraca sua fé pareça, ela ainda pode mover montanhas.", tags: ["fé"] },
  { texto: "A fé cresce na escuridão: é lá que aprendemos a confiar sem ver.", tags: ["fé"] },
  { texto: "Você foi criado para viver pela fé, não pelos seus medos.", tags: ["fé"] },
  { texto: "Sua fé é a ponte entre onde você está e onde Deus quer te levar.", tags: ["fé"] },
  { texto: "A fé verdadeira transforma impossibilidades em oportunidades divinas.", tags: ["fé"] },
  { texto: "Quando sua fé for testada, lembre-se: diamantes se formam sob pressão.", tags: ["fé"] },
  { texto: "Sua fé não precisa ser perfeita, apenas genuína e persistente.", tags: ["fé"] },
  { texto: "A fé é acreditar que Deus está trabalhando mesmo quando você não vê.", tags: ["fé"] },
  { texto: "Cada oração que você faz é um ato de fé que muda a atmosfera espiritual.", tags: ["fé"] },
  { texto: "Sua fé tem o poder de transformar não apenas você, mas todos ao seu redor.", tags: ["fé"] },
  { texto: "Viva pela fé, não pelas circunstâncias que tentam definir sua realidade.", tags: ["fé"] },
  { texto: "A fé é escolher a esperança quando todas as evidências sugerem desespero.", tags: ["fé"] },
  { texto: "Seu futuro está seguro nas mãos de Quem inspirou sua fé.", tags: ["fé"] },
  { texto: "A fé não é ausência de questionamentos, mas confiança apesar deles.", tags: ["fé"] },
  { texto: "Cada dia que você vive pela fé é uma vitória sobre a incredulidade.", tags: ["fé"] },
  { texto: "Sua fé é a chave que abre portas que a lógica humana nunca conseguiria.", tags: ["fé"] },
  { texto: "Não subestime o poder de uma fé simples mas sincera.", tags: ["fé"] },
  { texto: "A fé te conecta com o impossível e torna tudo possível.", tags: ["fé"] },
  { texto: "Quando você anda pela fé, cada passo é um milagre em si.", tags: ["fé"] },
  { texto: "Sua fé é o canal através do qual o céu se conecta com a terra.", tags: ["fé"] },
  { texto: "Permita que sua fé seja maior que seus problemas e menor que seu Deus.", tags: ["fé"] },

  // ESPERANÇA (25 frases)
  { texto: "Sua esperança é uma âncora que mantém seu coração firme em qualquer tempestade.", tags: ["esperança"] },
  { texto: "Mesmo na noite mais escura, a esperança sussurra: 'O amanhecer está chegando'.", tags: ["esperança"] },
  { texto: "A esperança é sua bússola interna que sempre aponta para o melhor caminho.", tags: ["esperança"] },
  { texto: "Você carrega dentro de si sementes de esperança que podem florescer a qualquer momento.", tags: ["esperança"] },
  { texto: "A esperança é a coragem de acreditar que os melhores dias ainda estão por vir.", tags: ["esperança"] },
  { texto: "Não deixe que as desilusões do passado roubem a esperança do seu futuro.", tags: ["esperança"] },
  { texto: "Cada novo dia traz consigo 1.440 minutos de possibilidades renovadas.", tags: ["esperança"] },
  { texto: "Sua esperança é um farol que ilumina o caminho para outros que perderam a direção.", tags: ["esperança"] },
  { texto: "A esperança transforma sonhos impossíveis em planos realizáveis.", tags: ["esperança"] },
  { texto: "Quando tudo parecer perdido, a esperança é sua lanterna na escuridão.", tags: ["esperança"] },
  { texto: "Você é prova viva de que a esperança nunca é desperdiçada.", tags: ["esperança"] },
  { texto: "A esperança é como ar puro: revigorante, essencial e disponível a todos.", tags: ["esperança"] },
  { texto: "Cultive esperança como quem planta flores: com paciência e expectativa.", tags: ["esperança"] },
  { texto: "Sua história não termina na dor; a esperança está escrevendo um final melhor.", tags: ["esperança"] },
  { texto: "A esperança é o combustível que mantém os sonhos vivos nos momentos difíceis.", tags: ["esperança"] },
  { texto: "Você pode não ver toda a estrada, mas pode ter esperança no destino.", tags: ["esperança"] },
  { texto: "A esperança é o remédio da alma para todas as feridas que a vida pode causar.", tags: ["esperança"] },
  { texto: "Cada respiração é um novo convite para renovar sua esperança.", tags: ["esperança"] },
  { texto: "Sua esperança hoje planta as sementes da sua alegria de amanhã.", tags: ["esperança"] },
  { texto: "A verdadeira esperança não nega a dor, mas acredita na possibilidade da cura.", tags: ["esperança"] },
  { texto: "Você foi criado para ser portador de esperança em um mundo que precisa dela.", tags: ["esperança"] },
  { texto: "A esperança é a força que te faz levantar quando tudo diz para desistir.", tags: ["esperança"] },
  { texto: "Mantenha viva a chama da esperança: ela aquecerá seu coração nos dias frios.", tags: ["esperança"] },
  { texto: "A esperança é sua companheira mais fiel nos momentos de solidão.", tags: ["esperança"] },
  { texto: "Quando você espera o melhor, se prepara para receber milagres.", tags: ["esperança"] },

  // PROTEÇÃO (15 frases)
  { texto: "Você está seguro nos braços do amor que nunca falha nem abandona.", tags: ["proteção"] },
  { texto: "Cada desafio que você enfrentou te tornou mais forte e resiliente.", tags: ["proteção"] },
  { texto: "Você é guardado por uma força maior que qualquer problema que possa surgir.", tags: ["proteção"] },
  { texto: "Sua vida é preciosa demais para ficar desprotegida; você tem um Guardião.", tags: ["proteção"] },
  { texto: "Mesmo quando você não percebe, você está sendo cuidado em cada detalhe.", tags: ["proteção"] },
  { texto: "Nenhuma arma forjada contra você prosperará, pois você tem proteção divina.", tags: ["proteção"] },
  { texto: "Você pode descansar tranquilo: Aquele que te protege nunca dorme.", tags: ["proteção"] },
  { texto: "Sua proteção não vem do que você faz, mas de quem você é: um filho amado.", tags: ["proteção"] },
  { texto: "Cada novo dia é prova de que você está sendo guardado para algo especial.", tags: ["proteção"] },
  { texto: "Você pode enfrentar qualquer gigante, pois não luta sozinho.", tags: ["proteção"] },
  { texto: "Sua vida tem um propósito tão importante que recebe proteção especial.", tags: ["proteção"] },
  { texto: "Caminhe com confiança: você tem a proteção do Rei do universo.", tags: ["proteção"] },
  { texto: "Nenhum mal prevalecerá sobre você, pois está coberto pela graça divina.", tags: ["proteção"] },
  { texto: "Você é mais protegido do que pode imaginar e mais amado do que consegue entender.", tags: ["proteção"] },
  { texto: "Descanse na certeza: você está seguro nas mãos que criaram o universo.", tags: ["proteção"] },

  // SABEDORIA (15 frases)
  { texto: "Sua experiência é sabedoria disfarçada; confie no que você aprendeu.", tags: ["sabedoria"] },
  { texto: "A sabedoria não vem da idade, mas da disposição de aprender com cada experiência.", tags: ["sabedoria"] },
  { texto: "Você tem acesso à sabedoria infinita; basta pedir e estar disposto a ouvir.", tags: ["sabedoria"] },
  { texto: "Cada erro que você cometeu contribuiu para a sabedoria que você tem hoje.", tags: ["sabedoria"] },
  { texto: "A verdadeira sabedoria é saber quando falar e quando permanecer em silêncio.", tags: ["sabedoria"] },
  { texto: "Você é mais sábio do que pensa; sua intuição é sabedoria sussurrando.", tags: ["sabedoria"] },
  { texto: "A sabedoria cresce quando você aplica o que aprendeu para ajudar outros.", tags: ["sabedoria"] },
  { texto: "Busque sabedoria mais que ouro; ela vale mais que qualquer tesouro material.", tags: ["sabedoria"] },
  { texto: "Sua sabedoria pode ser a luz que alguém precisa para encontrar o caminho.", tags: ["sabedoria"] },
  { texto: "A humildade é o berço da sabedoria; reconheça que sempre há mais para aprender.", tags: ["sabedoria"] },
  { texto: "Você tem dentro de si a sabedoria necessária para tomar as decisões certas.", tags: ["sabedoria"] },
  { texto: "A sabedoria verdadeira transforma conhecimento em compaixão pelos outros.", tags: ["sabedoria"] },
  { texto: "Cada pergunta que você faz é um passo em direção à sabedoria maior.", tags: ["sabedoria"] },
  { texto: "A sabedoria não é ter todas as respostas, mas saber onde encontrá-las.", tags: ["sabedoria"] },
  { texto: "Você pode escolher a sabedoria todos os dias através de suas decisões e atitudes.", tags: ["sabedoria"] },

  // ALEGRIA (15 frases)
  { texto: "Sua alegria é um presente que você dá ao mundo apenas por existir.", tags: ["alegria"] },
  { texto: "A alegria verdadeira brota de dentro e não depende das circunstâncias externas.", tags: ["alegria"] },
  { texto: "Você tem razões para se alegrar que nem sequer descobriu ainda.", tags: ["alegria"] },
  { texto: "Cada sorriso seu é um pequeno milagre que ilumina o dia de alguém.", tags: ["alegria"] },
  { texto: "A alegria é contagiosa; espalhe-a por onde for como quem espalha perfume.", tags: ["alegria"] },
  { texto: "Sua alegria não é determinada pelo que acontece, mas por quem você é.", tags: ["alegria"] },
  { texto: "Escolha encontrar alegria nas pequenas coisas; elas são as mais frequentes na vida.", tags: ["alegria"] },
  { texto: "Você foi criado para viver em alegria, não em tristeza constante.", tags: ["alegria"] },
  { texto: "A alegria é a música da alma; permita que a sua toque alto e claro.", tags: ["alegria"] },
  { texto: "Mesmo nos dias difíceis, há sempre um motivo pequeno para se alegrar.", tags: ["alegria"] },
  { texto: "Sua alegria autêntica é mais atrativa que qualquer máscara de felicidade forçada.", tags: ["alegria"] },
  { texto: "A alegria compartilhada é alegria multiplicada; divida a sua hoje.", tags: ["alegria"] },
  { texto: "Você tem o poder de transformar um dia comum em um dia especial pela sua alegria.", tags: ["alegria"] },
  { texto: "A alegria é uma escolha corajosa que você pode fazer independente das circunstâncias.", tags: ["alegria"] },
  { texto: "Sua alegria genuína é um testemunho do amor que vive dentro do seu coração.", tags: ["alegria"] },

  // PACIÊNCIA (15 frases)
  { texto: "Sua paciência é um investimento valioso que sempre rende frutos no momento certo.", tags: ["paciência"] },
  { texto: "A paciência transforma esperas em preparação para algo maior.", tags: ["paciência"] },
  { texto: "Você está sendo moldado durante esta temporada de paciência.", tags: ["paciência"] },
  { texto: "A paciência é uma virtude que cresce quanto mais você a pratica.", tags: ["paciência"] },
  { texto: "Cada momento de paciência é um investimento no seu crescimento pessoal.", tags: ["paciência"] },
  { texto: "Você pode escolher ver atrasos como redirecionamentos divinos.", tags: ["paciência"] },
  { texto: "A paciência é força disfarçada de gentileza; você é mais forte do que pensa.", tags: ["paciência"] },
  { texto: "As melhores coisas da vida crescem lentamente; seja paciente com o processo.", tags: ["paciência"] },
  { texto: "Sua paciência hoje está preparando você para as bênçãos de amanhã.", tags: ["paciência"] },
  { texto: "A paciência é autocompaixão em movimento; seja gentil consigo mesmo.", tags: ["paciência"] },
  { texto: "Você está no tempo certo, mesmo quando parece que está atrasado.", tags: ["paciência"] },
  { texto: "A paciência ensina que o valor das coisas não está na velocidade, mas na qualidade.", tags: ["paciência"] },
  { texto: "Cada dia de paciência é uma vitória sobre a ansiedade e a pressa.", tags: ["paciência"] },
  { texto: "Você pode confiar que o que é seu chegará no momento perfeito.", tags: ["paciência"] },
  { texto: "A paciência é o canal através do qual milagres chegam até você.", tags: ["paciência"] },

  // PERDÃO (15 frases)
  { texto: "Perdoar é um presente que você dá primeiro a si mesmo.", tags: ["perdão"] },
  { texto: "Você é livre para soltar o que te machucou e abraçar o que te cura.", tags: ["perdão"] },
  { texto: "O perdão não muda o passado, mas liberta o seu futuro.", tags: ["perdão"] },
  { texto: "Cada ato de perdão é uma vitória do amor sobre a amargura.", tags: ["perdão"] },
  { texto: "Você tem o poder de quebrar ciclos de dor através do perdão.", tags: ["perdão"] },
  { texto: "Perdoar não é esquecer, é escolher não deixar a dor controlar sua vida.", tags: ["perdão"] },
  { texto: "Sua capacidade de perdoar reflete a grandeza do seu coração.", tags: ["perdão"] },
  { texto: "O perdão é medicina para a alma; tome doses diárias.", tags: ["perdão"] },
  { texto: "Você pode escolher ser livre ao invés de carregar o peso do ressentimento.", tags: ["perdão"] },
  { texto: "Cada perdão que você oferece planta sementes de paz no mundo.", tags: ["perdão"] },
  { texto: "Perdoar é um ato de coragem que transforma vítimas em vencedores.", tags: ["perdão"] },
  { texto: "Você merece a paz que o perdão traz para sua alma.", tags: ["perdão"] },
  { texto: "O perdão é uma ponte que reconstrói relacionamentos e cura feridas profundas.", tags: ["perdão"] },
  { texto: "Sua jornada de cura começa com a decisão corajosa de perdoar.", tags: ["perdão"] },
  { texto: "Perdoar é escolher escrever uma nova história ao invés de ficar preso à antiga.", tags: ["perdão"] },

  // FORÇA (15 frases)
  { texto: "Você é mais resiliente do que qualquer situação que enfrenta.", tags: ["força"] },
  { texto: "Sua força interior é como um músculo que se fortalece com cada desafio superado.", tags: ["força"] },
  { texto: "Cada cicatriz que você carrega é prova da sua capacidade de cura.", tags: ["força"] },
  { texto: "Você tem uma força interior que nem você conhece completamente ainda.", tags: ["força"] },
  { texto: "A força real está na capacidade de continuar andando quando as pernas tremem.", tags: ["força"] },
  { texto: "Você foi forjado no fogo das dificuldades e saiu mais forte.", tags: ["força"] },
  { texto: "Sua força inspira outros a encontrarem a coragem que precisam.", tags: ["força"] },
  { texto: "Não subestime o poder da sua própria determinação.", tags: ["força"] },
  { texto: "Você pode suportar muito mais do que imagina e alcançar muito mais do que sonha.", tags: ["força"] },
  { texto: "Sua força cresce cada vez que você escolhe não desistir.", tags: ["força"] },
  { texto: "A força verdadeira é gentil, paciente e persistente.", tags: ["força"] },
  { texto: "Você tem força suficiente não apenas para sobreviver, mas para prosperar.", tags: ["força"] },
  { texto: "Cada batalha vencida adiciona uma nova camada à sua força interior.", tags: ["força"] },
  { texto: "Sua força não diminui quando você pede ajuda; na verdade, aumenta.", tags: ["força"] },
  { texto: "Você carrega dentro de si a força de gerações de pessoas corajosas.", tags: ["força"] },

  // HUMILDADE (10 frases)
  { texto: "Sua humildade é uma ponte que conecta você ao coração dos outros.", tags: ["humildade"] },
  { texto: "A humildade verdadeira não diminui você, mas eleva todos ao seu redor.", tags: ["humildade"] },
  { texto: "Você cresce quando reconhece que sempre há mais para aprender.", tags: ["humildade"] },
  { texto: "A humildade é a base sobre a qual todas as outras virtudes se constroem.", tags: ["humildade"] },
  { texto: "Sua disposição para servir outros revela a grandeza do seu caráter.", tags: ["humildade"] },
  { texto: "A humildade abre portas que a arrogância nunca conseguiria abrir.", tags: ["humildade"] },
  { texto: "Você pode ser confiante sem ser arrogante, forte sem ser rude.", tags: ["humildade"] },
  { texto: "A verdadeira grandeza se manifesta através da humildade genuína.", tags: ["humildade"] },
  { texto: "Sua humildade é um perfume suave que deixa todos ao redor mais felizes.", tags: ["humildade"] },
  { texto: "A humildade é o solo fértil onde as mais belas virtudes podem florescer.", tags: ["humildade"] },

  // MANSIDÃO (10 frases)
  { texto: "Sua mansidão é como água que molda a pedra mais dura com paciência e persistência.", tags: ["mansidão"] },
  { texto: "A mansidão desarma conflitos e constrói pontes onde havia muros.", tags: ["mansidão"] },
  { texto: "Você pode ser firme nos princípios e suave na abordagem.", tags: ["mansidão"] },
  { texto: "A mansidão transforma adversários em aliados através do amor.", tags: ["mansidão"] },
  { texto: "Sua gentileza tem o poder de curar feridas que palavras duras causaram.", tags: ["mansidão"] },
  { texto: "A mansidão é sabedoria que escolhe o caminho da compreensão ao invés da discussão.", tags: ["mansidão"] },
  { texto: "Você pode mudar o mundo através de atos simples de mansidão.", tags: ["mansidão"] },
  { texto: "A resposta mansa desvia o furor e constrói relacionamentos sólidos.", tags: ["mansidão"] },
  { texto: "Sua mansidão reflete um coração que entendeu o verdadeiro poder do amor.", tags: ["mansidão"] },
  { texto: "A mansidão é uma escolha corajosa que quebra ciclos de agressividade.", tags: ["mansidão"] },

  // CONSTÂNCIA (10 frases)
  { texto: "Sua constância é um testemunho da sua determinação em nunca desistir.", tags: ["constância"] },
  { texto: "A constância pequena todos os dias constrói grandes conquistas ao longo do tempo.", tags: ["constância"] },
  { texto: "Você pode confiar em si mesmo porque sua constância prova sua confiabilidade.", tags: ["constância"] },
  { texto: "A constância transforma sonhos em realidade através de ações persistentes.", tags: ["constância"] },
  { texto: "Sua fidelidade nas pequenas coisas te prepara para responsabilidades maiores.", tags: ["constância"] },
  { texto: "A constância é o ingrediente secreto que separa o sucesso do fracasso.", tags: ["constância"] },
  { texto: "Você está construindo algo lindo através da sua constância diária.", tags: ["constância"] },
  { texto: "A constância é amor em ação que persiste mesmo quando não se sente motivado.", tags: ["constância"] },
  { texto: "Sua constância hoje está plantando as sementes da sua vitória amanhã.", tags: ["constância"] },
  { texto: "Continue sendo constante; os resultados aparecerão no tempo certo.", tags: ["constância"] },

  // SERENIDADE (10 frases)
  { texto: "Sua serenidade é um oásis de paz em um mundo agitado.", tags: ["serenidade"] },
  { texto: "A serenidade não nega os problemas, mas os enfrenta com tranquilidade.", tags: ["serenidade"] },
  { texto: "Você pode ser o centro de calma em qualquer tempestade da vida.", tags: ["serenidade"] },
  { texto: "A serenidade é um presente que você dá a si mesmo e a todos ao seu redor.", tags: ["serenidade"] },
  { texto: "Sua serenidade interior reflete uma alma em paz com Deus.", tags: ["serenidade"] },
  { texto: "A serenidade cresce quando você aceita o que não pode mudar.", tags: ["serenidade"] },
  { texto: "Você pode escolher responder com serenidade mesmo em situações caóticas.", tags: ["serenidade"] },
  { texto: "A serenidade é sabedoria que encontrou seu lugar de descanso.", tags: ["serenidade"] },
  { texto: "Sua serenidade é magnética; as pessoas são atraídas pela paz que você irradia.", tags: ["serenidade"] },
  { texto: "A serenidade verdadeira vem de saber que você está nas mãos certas.", tags: ["serenidade"] },

  // GRATIDÃO (20 frases)
  { texto: "Cada manhã é um presente que você recebe sem merecer, mas com muito amor.", tags: ["gratidão"] },
  { texto: "Sua capacidade de ser grato transforma dias comuns em dias especiais.", tags: ["gratidão"] },
  { texto: "A gratidão é o filtro mágico que nos permite ver beleza em situações ordinárias.", tags: ["gratidão"] },
  { texto: "Você tem mais motivos para agradecer do que para reclamar, apenas precisa vê-los.", tags: ["gratidão"] },
  { texto: "A gratidão multiplica alegrias e divide tristezas em sua vida.", tags: ["gratidão"] },
  { texto: "Seu coração grato é um ímã que atrai mais bênçãos do que você pode imaginar.", tags: ["gratidão"] },
  { texto: "Cada respiração é um lembrete de que você tem vida para viver e amar.", tags: ["gratidão"] },
  { texto: "A gratidão transforma o pouco que você tem no suficiente para ser feliz.", tags: ["gratidão"] },
  { texto: "Você é uma coleção viva de milagres diários que merecem ser celebrados.", tags: ["gratidão"] },
  { texto: "A gratidão é a chave que abre seu coração para receber ainda mais amor.", tags: ["gratidão"] },
  { texto: "Cada pessoa que cruza seu caminho é um presente disfarçado de lição ou bênção.", tags: ["gratidão"] },
  { texto: "Sua vida é um livro cheio de capítulos pelos quais você pode ser grato.", tags: ["gratidão"] },
  { texto: "A gratidão é o perfume que você espalha quando reconhece as bondades recebidas.", tags: ["gratidão"] },
  { texto: "Você pode escolher ver problemas ou presentes; a gratidão muda sua perspectiva.", tags: ["gratidão"] },
  { texto: "Cada dificuldade superada é uma medalha de honra pela qual você pode agradecer.", tags: ["gratidão"] },
  { texto: "A gratidão é a linguagem do coração que todos compreendem intuitivamente.", tags: ["gratidão"] },
  { texto: "Você é rico em bênçãos que nem percebe; a gratidão abre seus olhos para elas.", tags: ["gratidão"] },
  { texto: "Cada novo amanhecer é uma nova oportunidade de recomeçar com gratidão.", tags: ["gratidão"] },
  { texto: "Sua gratidão hoje planta sementes de alegria que florescerão amanhã.", tags: ["gratidão"] },
  { texto: "A gratidão é o antídoto mais eficaz contra a tristeza e o descontentamento.", tags: ["gratidão"] },

  // CORAGEM (20 frases)
  { texto: "Sua coragem é como um músculo: quanto mais você usa, mais forte fica.", tags: ["coragem"] },
  { texto: "Você tem dentro de si a mesma coragem que moveu gigantes da história.", tags: ["coragem"] },
  { texto: "Cada passo corajoso que você dá inspira outros a serem corajosos também.", tags: ["coragem"] },
  { texto: "A coragem cresce quando você enfrenta seus medos ao invés de fugir deles.", tags: ["coragem"] },
  { texto: "Você foi criado para ser corajoso, não para viver uma vida de conformismo.", tags: ["coragem"] },
  { texto: "Sua coragem pode ser a chave que abre portas que pareciam impossíveis.", tags: ["coragem"] },
  { texto: "A verdadeira coragem é fazer o que é certo mesmo quando é difícil.", tags: ["coragem"] },
  { texto: "Você pode ser corajoso mesmo quando suas pernas estão tremendo.", tags: ["coragem"] },
  { texto: "Cada ato de coragem, por menor que seja, muda o mundo ao seu redor.", tags: ["coragem"] },
  { texto: "Sua coragem hoje pode ser a resposta às orações de alguém.", tags: ["coragem"] },
  { texto: "A coragem é uma escolha diária que você faz independente dos seus sentimentos.", tags: ["coragem"] },
  { texto: "Você é mais corajoso enfrentando suas batalhas do que evitando-as.", tags: ["coragem"] },
  { texto: "A coragem verdadeira está em ser vulnerável quando preciso.", tags: ["coragem"] },
  { texto: "Sua coragem de hoje escreve a história de vitória de amanhã.", tags: ["coragem"] },
  { texto: "A coragem é contagiosa; quando você é corajoso, encoraja outros a sê-lo também.", tags: ["coragem"] },
  { texto: "Você pode escolher a coragem mesmo quando todos ao redor escolhem o medo.", tags: ["coragem"] },
  { texto: "Cada desafio que você enfrenta corajosamente fortalece sua coragem para o próximo.", tags: ["coragem"] },
  { texto: "A coragem está disponível para você a cada momento, basta escolhê-la.", tags: ["coragem"] },
  { texto: "Você foi chamado para ser corajoso, não para viver na zona de conforto.", tags: ["coragem"] },
  { texto: "Sua coragem é uma ferramenta poderosa que pode transformar qualquer situação.", tags: ["coragem"] },

  // BONDADE (20 frases)
  { texto: "Sua bondade é como perfume: quanto mais você compartilha, mais você tem.", tags: ["bondade"] },
  { texto: "Cada ato de bondade que você pratica ecoa na eternidade.", tags: ["bondade"] },
  { texto: "Você tem o poder de iluminar o dia de alguém com um simples gesto bondoso.", tags: ["bondade"] },
  { texto: "A bondade não precisa ser grande para ser significativa na vida de alguém.", tags: ["bondade"] },
  { texto: "Seu coração bondoso é um ímã que atrai mais bondade para sua vida.", tags: ["bondade"] },
  { texto: "A bondade é a linguagem universal que todos compreendem, independente da idade.", tags: ["bondade"] },
  { texto: "Você pode mudar o mundo uma pessoa por vez através da sua bondade.", tags: ["bondade"] },
  { texto: "Cada momento é uma oportunidade nova de praticar bondade.", tags: ["bondade"] },
  { texto: "Sua bondade pode ser o milagre que alguém está esperando hoje.", tags: ["bondade"] },
  { texto: "A bondade verdadeira não espera reconhecimento, apenas se alegra em abençoar.", tags: ["bondade"] },
  { texto: "Você foi designado para espalhar bondade por onde quer que pise.", tags: ["bondade"] },
  { texto: "Cada pessoa que você trata com bondade leva um pedaço do céu consigo.", tags: ["bondade"] },
  { texto: "A bondade é um investimento que sempre retorna multiplicado.", tags: ["bondade"] },
  { texto: "Sua bondade hoje pode prevenir a tristeza de alguém amanhã.", tags: ["bondade"] },
  { texto: "A bondade é como mel: doce para quem dá e para quem recebe.", tags: ["bondade"] },
  { texto: "Você pode ser a razão pela qual alguém ainda acredita na bondade humana.", tags: ["bondade"] },
  { texto: "Cada gesto bondoso seu é uma semente de esperança plantada no mundo.", tags: ["bondade"] },
  { texto: "A bondade não custa nada para dar, mas vale tudo para quem recebe.", tags: ["bondade"] },
  { texto: "Você tem dentro de si uma fonte inesgotável de bondade para compartilhar.", tags: ["bondade"] },
  { texto: "Sua bondade é uma luz que brilha especialmente nos lugares mais escuros.", tags: ["bondade"] },

  // CUIDADO (20 frases)
  { texto: "Seu cuidado genuíno tem o poder de curar feridas invisíveis no coração de alguém.", tags: ["cuidado"] },
  { texto: "Cada pessoa que você cuida é um tesouro que enriquece sua própria alma.", tags: ["cuidado"] },
  { texto: "Você foi designado para ser guardião do bem-estar de quem Deus colocar no seu caminho.", tags: ["cuidado"] },
  { texto: "Seu cuidado atencioso pode ser a diferença entre desespero e esperança na vida de alguém.", tags: ["cuidado"] },
  { texto: "A forma como você cuida dos outros reflete o amor que Deus tem por você.", tags: ["cuidado"] },
  { texto: "Cada ato de cuidado que você oferece multiplica amor no mundo.", tags: ["cuidado"] },
  { texto: "Você tem mãos feitas para cuidar e um coração criado para amar.", tags: ["cuidado"] },
  { texto: "Seu cuidado pode transformar um momento difícil em uma memória de amor.", tags: ["cuidado"] },
  { texto: "Cada pessoa que você cuida com carinho leva consigo um pouco da sua alma.", tags: ["cuidado"] },
  { texto: "O cuidado verdadeiro não pergunta o que ganha, apenas o que pode dar.", tags: ["cuidado"] },
  { texto: "Você pode ser o anjo que alguém precisa através do seu cuidado dedicado.", tags: ["cuidado"] },
  { texto: "Seu cuidado atento hoje pode prevenir lágrimas de solidão amanhã.", tags: ["cuidado"] },
  { texto: "A qualidade do seu cuidado revela a profundidade do seu amor.", tags: ["cuidado"] },
  { texto: "Você é um jardim de cuidado onde almas feridas podem florescer novamente.", tags: ["cuidado"] },
  { texto: "Cada momento de cuidado que você oferece é um investimento no Reino do céu.", tags: ["cuidado"] },
  { texto: "Seu cuidado pode ser a ponte que reconecta alguém à esperança.", tags: ["cuidado"] },
  { texto: "A forma como você cuida hoje ensina outros sobre o amor incondicional.", tags: ["cuidado"] },
  { texto: "Você tem o privilégio de ser usado por Deus para cuidar de Suas crianças.", tags: ["cuidado"] },
  { texto: "Seu cuidado sincero pode ser o remédio que uma alma ferida precisa.", tags: ["cuidado"] },
  { texto: "Cada gesto de cuidado seu planta sementes de compaixão no mundo.", tags: ["cuidado"] },

  // SIMPLICIDADE (15 frases)
  { texto: "A simplicidade é sua superpotência secreta contra a ansiedade moderna.", tags: ["simplicidade"] },
  { texto: "Você encontra mais alegria nas coisas simples quando seu coração está em paz.", tags: ["simplicidade"] },
  { texto: "A simplicidade é a elegância da alma que descobriu onde está a verdadeira riqueza.", tags: ["simplicidade"] },
  { texto: "Sua vida simples pode ser mais rica em significado que vidas complicadas.", tags: ["simplicidade"] },
  { texto: "A simplicidade ensina que o suficiente é abundante quando há gratidão.", tags: ["simplicidade"] },
  { texto: "Você pode encontrar extraordinário contentamento em prazeres simples.", tags: ["simplicidade"] },
  { texto: "A simplicidade é clareza mental que corta através da confusão do mundo.", tags: ["simplicidade"] },
  { texto: "Sua simplicidade pode ser um testemunho poderoso em um mundo materialista.", tags: ["simplicidade"] },
  { texto: "A verdadeira simplicidade não é pobreza, é liberdade de escolher o que importa.", tags: ["simplicidade"] },
  { texto: "Você pode viver com simplicidade e ainda assim ter uma vida profundamente rica.", tags: ["simplicidade"] },
  { texto: "A simplicidade conecta você com a essência das coisas e das pessoas.", tags: ["simplicidade"] },
  { texto: "Sua simplicidade pode inspirar outros a questionar o que realmente precisam.", tags: ["simplicidade"] },
  { texto: "A simplicidade é a arte de viver bem com menos complicação.", tags: ["simplicidade"] },
  { texto: "Você descobre mais beleza na simplicidade do que na sofisticação forçada.", tags: ["simplicidade"] },
  { texto: "A simplicidade é uma escolha corajosa em um mundo que valoriza o excesso.", tags: ["simplicidade"] }
];