// lib/praticasData.ts

export interface Pratica {
  texto: string;
  tags: string[];
}

export const praticas: Pratica[] = [
  // PAZ (25 práticas)
  { texto: "Ofereça um abraço sincero para alguém que parece precisar de conforto.", tags: ["paz"] },
  { texto: "Medite por 5 minutos e depois ore por alguém que está enfrentando dificuldades.", tags: ["paz"] },
  { texto: "Envie uma mensagem de encorajamento para alguém que você não fala há tempo.", tags: ["paz"] },
  { texto: "Ajude um vizinho idoso com suas compras ou tarefas domésticas.", tags: ["paz"] },
  { texto: "Dedique 10 minutos para ouvir atentamente alguém que precisa desabafar.", tags: ["paz"] },
  { texto: "Prepare uma refeição caseira e leve para uma família necessitada.", tags: ["paz"] },
  { texto: "Visite um lar de idosos e passe tempo conversando com os residentes.", tags: ["paz"] },
  { texto: "Ofereça para cuidar dos filhos de um casal jovem para eles terem um tempo juntos.", tags: ["paz"] },
  { texto: "Plante uma flor ou árvore em um espaço público da sua comunidade.", tags: ["paz"] },
  { texto: "Organize um momento de oração em família pela paz no mundo.", tags: ["paz"] },
  { texto: "Doe roupas de inverno para pessoas em situação de rua.", tags: ["paz"] },
  { texto: "Escreva cartas de gratidão para professores ou profissionais de saúde.", tags: ["paz"] },
  { texto: "Ofereça água ou lanche para trabalhadores em serviço externo em dias quentes.", tags: ["paz"] },
  { texto: "Crie um pequeno jardim ou horta comunitária no seu bairro.", tags: ["paz"] },
  { texto: "Convide alguém solitário para almoçar ou tomar café na sua casa.", tags: ["paz"] },
  { texto: "Leia histórias para crianças em um hospital ou orfanato.", tags: ["paz"] },
  { texto: "Doe livros usados para uma biblioteca comunitária ou escola.", tags: ["paz"] },
  { texto: "Ajude um estudante com dificuldades em alguma matéria.", tags: ["paz"] },
  { texto: "Organize uma campanha de arrecadação de cobertores para o inverno.", tags: ["paz"] },
  { texto: "Ofereça carona para alguém que precisa ir ao médico.", tags: ["paz"] },
  { texto: "Prepare kits de higiene pessoal para distribuir a pessoas necessitadas.", tags: ["paz"] },
  { texto: "Passe um tempo brincando com crianças em um abrigo.", tags: ["paz"] },
  { texto: "Doe sangue ou se cadastre como doador de medula óssea.", tags: ["paz"] },
  { texto: "Ajude a limpar um parque ou praia da sua cidade.", tags: ["paz"] },
  { texto: "Ofereça aulas gratuitas de algo que você sabe fazer bem.", tags: ["paz"] },

  // CONFIANÇA (25 práticas)
  { texto: "Compartilhe seu testemunho de fé com alguém que está desanimado.", tags: ["confiança"] },
  { texto: "Ore por cinco pessoas diferentes e conte a elas que você orou.", tags: ["confiança"] },
  { texto: "Ajude financeiramente uma família que está passando por dificuldades.", tags: ["confiança"] },
  { texto: "Ofereça mentoria espiritual para um jovem da sua comunidade.", tags: ["confiança"] },
  { texto: "Organize um grupo de oração na sua vizinhança.", tags: ["confiança"] },
  { texto: "Visite alguém que está hospitalizado e ore com essa pessoa.", tags: ["confiança"] },
  { texto: "Doe uma Bíblia para alguém que demonstrou interesse na fé.", tags: ["confiança"] },
  { texto: "Convide um amigo não cristão para um evento da sua igreja.", tags: ["confiança"] },
  { texto: "Ofereça apoio prático (comida, transporte) para uma família enlutada.", tags: ["confiança"] },
  { texto: "Escreva versículos bíblicos encorajadores e distribua anonimamente.", tags: ["confiança"] },
  { texto: "Ore por alguém que está passando por dificuldades financeiras e ofereça apoio prático.", tags: ["confiança"] },
  { texto: "Ofereça sua casa como local de reunião para um pequeno grupo.", tags: ["confiança"] },
  { texto: "Ajude alguém desempregado a encontrar trabalho através da sua rede de contatos.", tags: ["confiança"] },
  { texto: "Adote uma família carente no Natal e providencie presentes e ceia.", tags: ["confiança"] },
  { texto: "Compartilhe uma habilidade que você sabe fazer com um jovem que deseja aprender.", tags: ["confiança"] },
  { texto: "Ore por um casal que você sabe que está passando por dificuldades no relacionamento.", tags: ["confiança"] },
  { texto: "Ajude com suas próprias mãos em um pequeno conserto ou serviço na casa de uma família necessitada.", tags: ["confiança"] },
  { texto: "Seja voluntário em um projeto missionário da sua igreja.", tags: ["confiança"] },
  { texto: "Doe materiais escolares para crianças de famílias com poucos recursos.", tags: ["confiança"] },
  { texto: "Ofereça hospedagem temporária para alguém em situação de emergência.", tags: ["confiança"] },
  { texto: "Guarde mensalmente uma pequena quantia para poder ajudar alguém em situação de emergência quando surgir.", tags: ["confiança"] },
  { texto: "Escreva uma carta de encorajamento para alguém que está em um centro de recuperação ou passando por reabilitação.", tags: ["confiança"] },
  { texto: "Organize retiros espirituais para grupos da sua comunidade.", tags: ["confiança"] },
  { texto: "Ajude idosos com suas finanças e documentos importantes.", tags: ["confiança"] },
  { texto: "Seja mentor de fé para alguém que está começando sua jornada cristã.", tags: ["confiança"] },

  // AMOR (25 práticas)
  { texto: "Escreva cartas de amor e gratidão para cada membro da sua família.", tags: ["amor"] },
  { texto: "Acolha com gentileza alguém de outra cultura ou cidade que chegou recentemente ao seu bairro.", tags: ["amor"] },
  { texto: "Organize jantares comunitários para pessoas solitárias.", tags: ["amor"] },
  { texto: "Cuide de animais abandonados em abrigos como voluntário.", tags: ["amor"] },
  { texto: "Faça atos inesperados de bondade durante a semana, sem esperar nada em troca.", tags: ["amor"] },
  { texto: "Ajude mães solteiras com cuidado das crianças ou tarefas domésticas.", tags: ["amor"] },
  { texto: "Organize festas de aniversário para crianças carentes.", tags: ["amor"] },
  { texto: "Visite asilos e adote um 'avô' ou 'avó' para visitar regularmente.", tags: ["amor"] },
  { texto: "Crie cestas básicas com carinho e distribua para famílias necessitadas.", tags: ["amor"] },
  { texto: "Ofereça abrigo e carinho para animais feridos até se recuperarem.", tags: ["amor"] },
  { texto: "Ensine crianças carentes a ler ou faça reforço escolar gratuito.", tags: ["amor"] },
  { texto: "Organize campanhas de doação de órgãos em sua comunidade.", tags: ["amor"] },
  { texto: "Dedique tempo de qualidade a um jovem da sua família ou vizinhança que precisa de atenção.", tags: ["amor"] },
  { texto: "Crie um projeto de correspondência com idosos solitários.", tags: ["amor"] },
  { texto: "Alivie a carga de um cuidador esgotado oferecendo descanso, companhia ou assumindo algumas de suas tarefas por um tempo.", tags: ["amor"] },
  { texto: "Monte kits de bebê para mães adolescentes sem recursos.", tags: ["amor"] },
  { texto: "Organize mutirões de limpeza e pintura em casas de famílias carentes.", tags: ["amor"] },
  { texto: "Conecte pessoas que enfrentam a mesma condição de saúde para que possam se apoiar mutuamente.", tags: ["amor"] },
  { texto: "Ofereça transporte gratuito para idosos irem a consultas médicas.", tags: ["amor"] },
  { texto: "Faça cobertores ou roupas de tricô para bebês prematuros.", tags: ["amor"] },
  { texto: "Organize encontros entre gerações para troca de experiências.", tags: ["amor"] },
  { texto: "Crie hortas comunitárias e ensine cultivo sustentável.", tags: ["amor"] },
  { texto: "Visite ou ligue para um familiar de doente terminal e ofereça companhia, escuta e oração.", tags: ["amor"] },
  { texto: "Monte bibliotecas gratuitas em pontos de ônibus ou praças.", tags: ["amor"] },
  { texto: "Ofereça ajuda prática a um casal recém-casado com poucos recursos, como preparar uma refeição ou ajudar com tarefas domésticas.", tags: ["amor"] },

  // FÉ (25 práticas)
  { texto: "Distribua Bíblias gratuitamente em locais públicos com movimento.", tags: ["fé"] },
  { texto: "Organize estudos bíblicos em casas para alcançar não cristãos.", tags: ["fé"] },
  { texto: "Faça evangelismo pessoal oferecendo oração nas ruas.", tags: ["fé"] },
  { texto: "Crie um ministério de visitação para membros afastados da igreja.", tags: ["fé"] },
  { texto: "Organize eventos evangelísticos com música e testemunhos.", tags: ["fé"] },
  { texto: "Ministre para pessoas em hospitais através de oração e palavra.", tags: ["fé"] },
  { texto: "Crie materiais evangelísticos criativos para distribuição.", tags: ["fé"] },
  { texto: "Ofereça cursos bíblicos gratuitos para a comunidade.", tags: ["fé"] },
  { texto: "Leve uma palavra de fé e esperança a pessoas que você encontra no dia a dia.", tags: ["fé"] },
  { texto: "Compartilhe um versículo bíblico que te fortaleceu com alguém que está passando por dificuldades.", tags: ["fé"] },
  { texto: "Ministre para viciados em recuperação com base bíblica.", tags: ["fé"] },
  { texto: "Crie grupos de discipulado para novos convertidos.", tags: ["fé"] },
  { texto: "Esteja disponível para ouvir com atenção e orar com alguém que está em crise.", tags: ["fé"] },
  { texto: "Leia a Bíblia por pelo menos 15 minutos hoje e compartilhe o que aprendeu com alguém.", tags: ["fé"] },
  { texto: "Trate com dignidade e respeito todas as pessoas que você encontrar hoje, independentemente de quem sejam.", tags: ["fé"] },
  { texto: "Crie ministério específico para alcançar jovens nas escolas.", tags: ["fé"] },
  { texto: "Ofereça ministração espiritual em empresas e escritórios.", tags: ["fé"] },
  { texto: "Organize retiros de oração e jejum para intercessão.", tags: ["fé"] },
  { texto: "Ministre para familiares de presos através de visitação.", tags: ["fé"] },
  { texto: "Crie pontos de oração em locais estratégicos da cidade.", tags: ["fé"] },
  { texto: "Ore com fervor por pessoas que você conhece que estão presas a vícios ou situações difíceis.", tags: ["fé"] },
  { texto: "Organize vigílias de oração por avivamento na sua região.", tags: ["fé"] },
  { texto: "Ministre através de dons espirituais em locais públicos.", tags: ["fé"] },
  { texto: "Entre em contato com um amigo que se afastou da fé e mostre que você se importa com ele.", tags: ["fé"] },
  { texto: "Dedique um tempo específico do seu dia para interceder em oração por sua família e comunidade.", tags: ["fé"] },

  // ESPERANÇA (25 práticas)
  { texto: "Visite unidades de tratamento de câncer levando esperança e oração.", tags: ["esperança"] },
  { texto: "Crie cartas de esperança para pessoas que tentaram suicídio.", tags: ["esperança"] },
  { texto: "Esteja presente para uma pessoa que você sabe que está passando por um período de depressão, ligando ou visitando regularmente.", tags: ["esperança"] },
  { texto: "Ajude famílias que perderam suas casas a reconstruir suas vidas.", tags: ["esperança"] },
  { texto: "Leve conforto e uma palavra de esperança para alguém que está de luto, estando presente com empatia e oração.", tags: ["esperança"] },
  { texto: "Passe um tempo brincando ou desenhando com crianças que estão passando por momentos difíceis, trazendo leveza e alegria.", tags: ["esperança"] },
  { texto: "Incentive e apoie um jovem em seus estudos, ajudando com material didático ou orientação para buscar oportunidades educacionais.", tags: ["esperança"] },
  { texto: "Organize campanhas contra o bullying nas escolas.", tags: ["esperança"] },
  { texto: "Esteja presente com empatia para pessoas que carregam traumas, ouvindo sem julgamento e orando com elas.", tags: ["esperança"] },
  { texto: "Apoie e acolha com compaixão uma mulher que esteja passando por situação de violência, ajudando-a a buscar os recursos disponíveis.", tags: ["esperança"] },
  { texto: "Trate com dignidade e acolhimento uma pessoa que está tentando recomeçar a vida após erros do passado.", tags: ["esperança"] },
  { texto: "Participe ativamente de iniciativas de esperança em sua comunidade, levando sua presença e alegria.", tags: ["esperança"] },
  { texto: "Visite alguém com doença grave e passe tempo de qualidade com essa pessoa, oferecendo companhia e esperança.", tags: ["esperança"] },
  { texto: "Demonstre interesse genuíno pela saúde emocional de jovens ao seu redor, perguntando como estão e ouvindo com atenção.", tags: ["esperança"] },
  { texto: "Ofereça apoio para famílias de pessoas desaparecidas.", tags: ["esperança"] },
  { texto: "Doe itens essenciais ou ajude de forma prática famílias afetadas por desastres naturais ou emergências.", tags: ["esperança"] },
  { texto: "Ministre para pessoas com deficiência mostrando seu valor.", tags: ["esperança"] },
  { texto: "Participe como voluntário em alguma iniciativa comunitária já existente no seu bairro ou cidade.", tags: ["esperança"] },
  { texto: "Divulgue o trabalho ou empreendimento de alguém com poucos recursos para ajudar essa pessoa a conquistar clientes.", tags: ["esperança"] },
  { texto: "Dê uma segunda chance a alguém que está recomeçando a vida, sem preconceito, tratando-o com dignidade e respeito.", tags: ["esperança"] },
  { texto: "Trate imigrantes e estrangeiros com acolhimento e respeito, ajudando com o que estiver ao seu alcance.", tags: ["esperança"] },
  { texto: "Indique uma vaga de trabalho ou oportunidade que você viu para alguém que está há muito tempo desempregado.", tags: ["esperança"] },
  { texto: "Ofereça alfabetização para adultos que não sabem ler.", tags: ["esperança"] },
  { texto: "Organize campanhas de doação de sangue em hospitais.", tags: ["esperança"] },
  { texto: "Ministre esperança através da música em locais de sofrimento.", tags: ["esperança"] },

  // PROTEÇÃO (15 práticas)
  { texto: "Conheça seus vizinhos pelo nome e estabeleça uma rede de cuidado mútuo no seu bairro.", tags: ["proteção"] },
  { texto: "Doe agasalhos, cobertores ou kits de higiene para crianças em situação de vulnerabilidade.", tags: ["proteção"] },
  { texto: "Ajude uma pessoa vulnerável a entender seus direitos básicos ou a encontrar os serviços públicos de que precisa.", tags: ["proteção"] },
  { texto: "Visite ou telefone regularmente para um idoso que mora sozinho para garantir que está bem.", tags: ["proteção"] },
  { texto: "Apoie financeiramente ou como voluntário organizações que cuidam de mulheres e crianças em situação de vulnerabilidade.", tags: ["proteção"] },
  { texto: "Ofereça escolta segura para crianças no caminho da escola.", tags: ["proteção"] },
  { texto: "Acompanhe uma mulher que se sente insegura em seu caminho ou ofereça apoio prático em situações de risco.", tags: ["proteção"] },
  { texto: "Fique atento a sinais de violência doméstica na sua vizinhança e saiba como acionar os serviços de ajuda disponíveis.", tags: ["proteção"] },
  { texto: "Acolha com amor um jovem que está passando por crise familiar e ofereça suporte emocional e prático.", tags: ["proteção"] },
  { texto: "Informe-se sobre os sinais de exploração humana e compartilhe esse conhecimento com pessoas próximas para proteger a comunidade.", tags: ["proteção"] },
  { texto: "Ore por pessoas que enfrentam situações de injustiça ou perigo e ofereça sua companhia e suporte emocional.", tags: ["proteção"] },
  { texto: "Interceda em oração por líderes cristãos que enfrentam pressões e dificuldades em seu ministério.", tags: ["proteção"] },
  { texto: "Ore e demonstre solidariedade a cristãos que enfrentam discriminação ou dificuldades por causa de sua fé.", tags: ["proteção"] },
  { texto: "Leve alimentos ou agasalhos para pessoas em situação de rua em dias frios ou de chuva.", tags: ["proteção"] },
  { texto: "Defenda verbalmente alguém que está sendo tratado de forma injusta em sua presença, com calma e firmeza.", tags: ["proteção"] },

  // SABEDORIA (15 práticas)
  { texto: "Ofereça mentoria profissional gratuita para jovens em início de carreira.", tags: ["sabedoria"] },
  { texto: "Crie grupos de estudo bíblico focados em sabedoria prática.", tags: ["sabedoria"] },
  { texto: "Organize workshops de educação financeira para famílias carentes.", tags: ["sabedoria"] },
  { texto: "Ofereça consultoria gratuita para pequenos empreendedores.", tags: ["sabedoria"] },
  { texto: "Crie bibliotecas comunitárias com livros de desenvolvimento pessoal.", tags: ["sabedoria"] },
  { texto: "Organize palestras sobre tomada de decisões baseadas em princípios bíblicos.", tags: ["sabedoria"] },
  { texto: "Compartilhe com um jovem noivo ou noiva um aprendizado valioso sobre relacionamento que você já viveu.", tags: ["sabedoria"] },
  { texto: "Crie grupos de apoio para pais baseados em princípios cristãos.", tags: ["sabedoria"] },
  { texto: "Organize cursos de resolução de conflitos usando sabedoria bíblica.", tags: ["sabedoria"] },
  { texto: "Ofereça orientação vocacional para jovens usando dons espirituais.", tags: ["sabedoria"] },
  { texto: "Crie círculos de anciãos para compartilhar sabedoria de vida.", tags: ["sabedoria"] },
  { texto: "Organize seminários sobre ética cristã para profissionais.", tags: ["sabedoria"] },
  { texto: "Incentive alguém que está desanimado com seus objetivos, compartilhando palavras de encorajamento baseadas em princípios bíblicos.", tags: ["sabedoria"] },
  { texto: "Crie grupos de discernimento para tomadas de decisões importantes.", tags: ["sabedoria"] },
  { texto: "Organize retiros de busca por direção divina para grandes decisões.", tags: ["sabedoria"] },

  // ALEGRIA (15 práticas)
  { texto: "Organize festas surpresa para pessoas que estão passando por momentos difíceis.", tags: ["alegria"] },
  { texto: "Crie grupos de palhaços cristãos para visitar hospitais infantis.", tags: ["alegria"] },
  { texto: "Ofereça aulas de dança gratuitas para idosos em asilos.", tags: ["alegria"] },
  { texto: "Organize piqueniques comunitários para famílias de baixa renda.", tags: ["alegria"] },
  { texto: "Crie coral comunitário para levar música a casas de repouso.", tags: ["alegria"] },
  { texto: "Ofereça sessões de cinema gratuito para crianças carentes.", tags: ["alegria"] },
  { texto: "Organize jogos e brincadeiras em praças públicas aos finais de semana.", tags: ["alegria"] },
  { texto: "Crie festivais de talentos para crianças e jovens da comunidade.", tags: ["alegria"] },
  { texto: "Ofereça oficinas de arte e artesanato para pessoas deprimidas.", tags: ["alegria"] },
  { texto: "Organize excursões gratuitas para famílias que nunca saíram da cidade.", tags: ["alegria"] },
  { texto: "Crie grupos de contadores de histórias para entreter crianças.", tags: ["alegria"] },
  { texto: "Ofereça aulas de culinária comunitária com receitas alegres.", tags: ["alegria"] },
  { texto: "Organize competições esportivas amadoras entre bairros.", tags: ["alegria"] },
  { texto: "Crie clubes de leitura para compartilhar livros inspiradores.", tags: ["alegria"] },
  { texto: "Ofereça sessões de musicoterapia para pessoas hospitalizadas.", tags: ["alegria"] },

  // PACIÊNCIA (15 práticas)
  { texto: "Ofereça aulas de reforço escolar para crianças com dificuldades de aprendizagem.", tags: ["paciência"] },
  { texto: "Crie grupos de apoio para cuidadores de pessoas com Alzheimer.", tags: ["paciência"] },
  { texto: "Organize atividades terapêuticas para crianças com necessidades especiais.", tags: ["paciência"] },
  { texto: "Ofereça acompanhamento para pessoas em processo de alfabetização adulta.", tags: ["paciência"] },
  { texto: "Crie programas de visitação para pessoas com depressão severa.", tags: ["paciência"] },
  { texto: "Organize grupos de oração para situações que requerem espera prolongada.", tags: ["paciência"] },
  { texto: "Ofereça mentoria para jovens com histórico de problemas comportamentais.", tags: ["paciência"] },
  { texto: "Crie grupos de apoio para casais enfrentando infertilidade.", tags: ["paciência"] },
  { texto: "Organize atividades para famílias com crianças autistas.", tags: ["paciência"] },
  { texto: "Ofereça acompanhamento para pessoas em processo de reabilitação.", tags: ["paciência"] },
  { texto: "Crie programas de integração para imigrantes aprendendo português.", tags: ["paciência"] },
  { texto: "Convide um idoso do seu bairro para uma caminhada tranquila ao ar livre.", tags: ["paciência"] },
  { texto: "Ofereça apoio para pais de crianças com deficiências múltiplas.", tags: ["paciência"] },
  { texto: "Crie grupos de apoio para pessoas aguardando transplantes de órgãos.", tags: ["paciência"] },
  { texto: "Organize atividades de estimulação cognitiva para pessoas com demência.", tags: ["paciência"] },

  // PERDÃO (15 práticas)
  { texto: "Organize círculos de justiça restaurativa entre vítimas e agressores.", tags: ["perdão"] },
  { texto: "Crie grupos de apoio para familiares de vítimas de crimes violentos.", tags: ["perdão"] },
  { texto: "Ofereça mediação de conflitos familiares baseada no perdão cristão.", tags: ["perdão"] },
  { texto: "Organize retiros de cura interior para pessoas feridas emocionalmente.", tags: ["perdão"] },
  { texto: "Crie programas de reconciliação entre comunidades em conflito.", tags: ["perdão"] },
  { texto: "Ofereça aconselhamento para casais em processo de separação.", tags: ["perdão"] },
  { texto: "Organize encontros entre pais e filhos afastados por mágoas antigas.", tags: ["perdão"] },
  { texto: "Crie grupos de apoio para pessoas traídas em relacionamentos.", tags: ["perdão"] },
  { texto: "Ofereça ministração de cura emocional para vítimas de abuso.", tags: ["perdão"] },
  { texto: "Organize workshops sobre perdão em escolas e universidades.", tags: ["perdão"] },
  { texto: "Crie programas de reconciliação racial em comunidades divididas.", tags: ["perdão"] },
  { texto: "Ofereça apoio para famílias divididas por questões políticas ou religiosas.", tags: ["perdão"] },
  { texto: "Organize cerimônias simbólicas de perdão em datas significativas.", tags: ["perdão"] },
  { texto: "Crie grupos de apoio para pessoas que precisam perdoar a si mesmas.", tags: ["perdão"] },
  { texto: "Ofereça treinamento em comunicação não violenta para resolver conflitos.", tags: ["perdão"] },

  // FORÇA (15 práticas)
  { texto: "Organize grupos de exercícios gratuitos para pessoas em recuperação.", tags: ["força"] },
  { texto: "Fortaleça uma mulher ao seu redor que passou por situação difícil, lembrando-a do seu valor e capacidade.", tags: ["força"] },
  { texto: "Inspire jovens ao seu redor a desenvolverem seu potencial de liderança por meio do seu próprio exemplo.", tags: ["força"] },
  { texto: "Organize competições esportivas para pessoas com deficiência.", tags: ["força"] },
  { texto: "Crie grupos de apoio mútuo para pessoas enfrentando vícios.", tags: ["força"] },
  { texto: "Acredite no potencial de pessoas que estão recomeçando, tratando-as com respeito e incentivando seus esforços.", tags: ["força"] },
  { texto: "Organize mutirões de construção usando força física comunitária.", tags: ["força"] },
  { texto: "Crie programas de autoestima para adolescentes em vulnerabilidade.", tags: ["força"] },
  { texto: "Encoraje e apoie pessoas desempregadas ao seu redor, ajudando-as a atualizar currículos ou encontrar oportunidades.", tags: ["força"] },
  { texto: "Organize grupos de caminhada e exercícios para pessoas com depressão.", tags: ["força"] },
  { texto: "Crie programas de desenvolvimento de talentos para jovens.", tags: ["força"] },
  { texto: "Seja uma referência de vida saudável para um jovem que não tem muitos adultos de exemplo ao seu redor.", tags: ["força"] },
  { texto: "Organize competições de talentos para pessoas com baixa autoestima.", tags: ["força"] },
  { texto: "Crie grupos de empoderamento econômico para mulheres chefes de família.", tags: ["força"] },
  { texto: "Seja uma presença positiva e estabilizadora em seu bairro, construindo laços de confiança com os moradores.", tags: ["força"] },

  // HUMILDADE (10 práticas)
  { texto: "Sirva refeições em albergues sem buscar reconhecimento ou publicidade.", tags: ["humildade"] },
  { texto: "Limpe banheiros públicos ou espaços comunitários anonimamente.", tags: ["humildade"] },
  { texto: "Ofereça para lavar os pés de moradores de rua como Jesus fez.", tags: ["humildade"] },
  { texto: "Trabalhe em mutirões de limpeza de igrejas de outras denominações.", tags: ["humildade"] },
  { texto: "Sirva como ajudante em eventos sem querer aparecer ou ser mencionado.", tags: ["humildade"] },
  { texto: "Organize limpeza de casas para pessoas impossibilitadas.", tags: ["humildade"] },
  { texto: "Ofereça para fazer trabalhos pesados que ninguém quer fazer.", tags: ["humildade"] },
  { texto: "Sirva como voluntário em tarefas de bastidores em eventos comunitários.", tags: ["humildade"] },
  { texto: "Cuide do jardim ou limpeza de espaços públicos sem esperar pagamento.", tags: ["humildade"] },
  { texto: "Ofereça seus serviços profissionais gratuitamente para quem não pode pagar.", tags: ["humildade"] },

  // MANSIDÃO (10 práticas)
  { texto: "Pratique comunicação não violenta em conflitos familiares.", tags: ["mansidão"] },
  { texto: "Ofereça mediação pacífica em disputas entre vizinhos.", tags: ["mansidão"] },
  { texto: "Ensine técnicas de resolução pacífica de conflitos para crianças.", tags: ["mansidão"] },
  { texto: "Responda com gentileza a pessoas que te tratam mal.", tags: ["mansidão"] },
  { texto: "Organize círculos de diálogo para resolver tensões comunitárias.", tags: ["mansidão"] },
  { texto: "Pratique a escuta ativa sem julgar pessoas que te procuram.", tags: ["mansidão"] },
  { texto: "Ofereça abraços e palavras suaves para pessoas irritadas.", tags: ["mansidão"] },
  { texto: "Ensine controle da raiva através do exemplo da mansidão cristã.", tags: ["mansidão"] },
  { texto: "Organize grupos de apoio para pessoas com problemas de temperamento.", tags: ["mansidão"] },
  { texto: "Pratique o perdão imediato quando alguém te ofender.", tags: ["mansidão"] },

  // CONSTÂNCIA (10 práticas)
  { texto: "Visite o mesmo asilo semanalmente pelo período de um ano.", tags: ["constância"] },
  { texto: "Adote uma família carente e ajude consistentemente por anos.", tags: ["constância"] },
  { texto: "Organize um projeto de leitura semanal para crianças carentes.", tags: ["constância"] },
  { texto: "Mantenha um grupo de oração que se encontra regularmente há anos.", tags: ["constância"] },
  { texto: "Cuide consistentemente do mesmo jardim comunitário por longo prazo.", tags: ["constância"] },
  { texto: "Visite mensalmente as mesmas pessoas hospitalizadas cronicamente.", tags: ["constância"] },
  { texto: "Mantenha um programa de mentoria com o mesmo jovem por anos.", tags: ["constância"] },
  { texto: "Organize o mesmo evento beneficente anual por uma década.", tags: ["constância"] },
  { texto: "Cuide consistentemente da mesma pessoa idosa por anos.", tags: ["constância"] },
  { texto: "Mantenha um pequeno grupo bíblico funcionando por muitos anos.", tags: ["constância"] },

  // SERENIDADE (10 práticas)
  { texto: "Crie espaços de meditação e oração em hospitais e clínicas.", tags: ["serenidade"] },
  { texto: "Ofereça sessões de relaxamento para pessoas com ansiedade.", tags: ["serenidade"] },
  { texto: "Organize retiros de silêncio e contemplação para líderes estressados.", tags: ["serenidade"] },
  { texto: "Crie jardins terapêuticos em espaços urbanos movimentados.", tags: ["serenidade"] },
  { texto: "Pratique exercícios de respiração e oração contemplativa para cultivar a serenidade interior.", tags: ["serenidade"] },
  { texto: "Organize momentos de quietude e paz em eventos agitados.", tags: ["serenidade"] },
  { texto: "Crie ambientes calmos para estudantes durante épocas de prova.", tags: ["serenidade"] },
  { texto: "Ofereça presença serena para pessoas em momentos de crise.", tags: ["serenidade"] },
  { texto: "Organize vigílias silenciosas de oração em locais de trauma.", tags: ["serenidade"] },
  { texto: "Crie espaços de descanso para cuidadores esgotados.", tags: ["serenidade"] },

  // GRATIDÃO (20 práticas)
  { texto: "Escreva cartas de gratidão para pessoas que impactaram positivamente sua vida.", tags: ["gratidão"] },
  { texto: "Organize uma campanha de agradecimento para profissionais essenciais da cidade.", tags: ["gratidão"] },
  { texto: "Crie um mural comunitário onde pessoas possam expressar gratidão.", tags: ["gratidão"] },
  { texto: "Ofereça cestas de presentes para bombeiros, policiais e médicos.", tags: ["gratidão"] },
  { texto: "Organize jantares de agradecimento para voluntários de organizações beneficentes.", tags: ["gratidão"] },
  { texto: "Crie vídeos de agradecimento para professores no dia do professor.", tags: ["gratidão"] },
  { texto: "Prepare um momento especial de gratidão para uma mãe que você conhece, como um café da manhã caprichado ou um bilhete de agradecimento.", tags: ["gratidão"] },
  { texto: "Organize cerimônias de reconhecimento para heróis anônimos da comunidade.", tags: ["gratidão"] },
  { texto: "Crie um livro de gratidão coletivo com histórias inspiradoras.", tags: ["gratidão"] },
  { texto: "Ofereça jantares especiais para casais que completam bodas.", tags: ["gratidão"] },
  { texto: "Organize encontros entre gerações para troca de histórias e agradecimentos.", tags: ["gratidão"] },
  { texto: "Crie campanhas de gratidão nas redes sociais destacando pessoas especiais.", tags: ["gratidão"] },
  { texto: "Ofereça flores e cartões de agradecimento para enfermeiros em hospitais.", tags: ["gratidão"] },
  { texto: "Organize saraus onde pessoas compartilham gratidão através da arte.", tags: ["gratidão"] },
  { texto: "Crie um jardim da gratidão com placas de agradecimento.", tags: ["gratidão"] },
  { texto: "Ofereça cafés da manhã especiais para garis e trabalhadores de limpeza.", tags: ["gratidão"] },
  { texto: "Expresse gratidão publicamente, elogiando alguém em voz alta na frente de outras pessoas.", tags: ["gratidão"] },
  { texto: "Crie podcasts destacando histórias de gratidão da comunidade.", tags: ["gratidão"] },
  { texto: "Ofereça experiências especiais para pessoas que dedicaram suas vidas ao serviço.", tags: ["gratidão"] },
  { texto: "Organize festivais anuais de gratidão com apresentações e homenagens.", tags: ["gratidão"] },

  // CORAGEM (20 práticas)
  { texto: "Organize grupos de apoio para pessoas que querem superar vícios.", tags: ["coragem"] },
  { texto: "Crie programas de empoderamento para vítimas de bullying.", tags: ["coragem"] },
  { texto: "Ofereça treinamento em primeiros socorros para pessoas comuns.", tags: ["coragem"] },
  { texto: "Organize campanhas contra injustiças sociais em sua comunidade.", tags: ["coragem"] },
  { texto: "Crie grupos de apoio para pessoas que querem mudar de carreira.", tags: ["coragem"] },
  { texto: "Encoraje um jovem tímido a descobrir seus dons, destacando suas qualidades e apoiando suas iniciativas.", tags: ["coragem"] },
  { texto: "Posicione-se contra a violência doméstica em conversas no dia a dia, sem medo de defender o que é certo.", tags: ["coragem"] },
  { texto: "Incentive alguém que deseja empreender compartilhando sua experiência e motivando-o a dar os primeiros passos.", tags: ["coragem"] },
  { texto: "Compartilhe com as mulheres ao seu redor dicas práticas de segurança pessoal para o dia a dia.", tags: ["coragem"] },
  { texto: "Organize grupos de oração por coragem em hospitais de câncer.", tags: ["coragem"] },
  { texto: "Fale abertamente sobre saúde mental com pessoas próximas, quebrando o silêncio e incentivando o cuidado emocional.", tags: ["coragem"] },
  { texto: "Ofereça apoio para pessoas que querem denunciar crimes.", tags: ["coragem"] },
  { texto: "Convide um amigo que tem medo de experimentar coisas novas para uma atividade simples e encorajadora que vocês façam juntos.", tags: ["coragem"] },
  { texto: "Crie grupos de apoio para pais de filhos com deficiência.", tags: ["coragem"] },
  { texto: "Encoraje alguém com fobia social a se expressar em ambientes seguros, valorizando cada pequeno avanço.", tags: ["coragem"] },
  { texto: "Envolva-se na vida da sua comunidade com coragem, participando de reuniões de moradores ou de iniciativas locais.", tags: ["coragem"] },
  { texto: "Acolha sem julgamento alguém que está lutando para superar um vício e ofereça sua amizade e incentivo.", tags: ["coragem"] },
  { texto: "Defenda com firmeza alguém que está sendo discriminado, manifestando-se a favor da dignidade e igualdade.", tags: ["coragem"] },
  { texto: "Organize grupos de apoio para pessoas que enfrentam doenças graves.", tags: ["coragem"] },
  { texto: "Crie campanhas de doação de órgãos encorajando pessoas a serem doadoras.", tags: ["coragem"] },

  // BONDADE (20 práticas)
  { texto: "Pague o pedido de quem está atrás de você na fila do café.", tags: ["bondade"] },
  { texto: "Deixe moedas em máquinas de doces para crianças encontrarem.", tags: ["bondade"] },
  { texto: "Ofereça guarda-chuva para pessoas na chuva que não têm.", tags: ["bondade"] },
  { texto: "Crie pequenos cartões com mensagens positivas e distribua aleatoriamente.", tags: ["bondade"] },
  { texto: "Ofereça para carregar as compras de idosos até o carro.", tags: ["bondade"] },
  { texto: "Deixe flores anônimas na mesa de trabalho de pessoas estressadas.", tags: ["bondade"] },
  { texto: "Pague estacionamento para carros que estão vencendo.", tags: ["bondade"] },
  { texto: "Ofereça lanches para pessoas fazendo fila em bancos.", tags: ["bondade"] },
  { texto: "Crie kits de primeiros socorros e distribua para motoristas.", tags: ["bondade"] },
  { texto: "Deixe livros com dedicatórias em bancos de praças.", tags: ["bondade"] },
  { texto: "Ofereça água gelada para pessoas trabalhando no calor.", tags: ["bondade"] },
  { texto: "Crie cestas de café da manhã para porteiros e seguranças.", tags: ["bondade"] },
  { texto: "Ofereça para passear com cães de vizinhos idosos.", tags: ["bondade"] },
  { texto: "Deixe notas de encorajamento em espelhos de banheiros públicos.", tags: ["bondade"] },
  { texto: "Pague pedágios para carros que vêm atrás de você.", tags: ["bondade"] },
  { texto: "Ofereça carregadores de celular em locais públicos.", tags: ["bondade"] },
  { texto: "Crie pequenos jardins em canteiros abandonados.", tags: ["bondade"] },
  { texto: "Ofereça para fotografar famílias em pontos turísticos.", tags: ["bondade"] },
  { texto: "Deixe dinheiro em livros de bibliotecas com mensagens motivadoras.", tags: ["bondade"] },
  { texto: "Organize surpresas coletivas para funcionários dedicados.", tags: ["bondade"] },

  // CUIDADO (20 práticas)
  { texto: "Organize cuidadores voluntários para pais de recém-nascidos.", tags: ["cuidado"] },
  { texto: "Crie rede de apoio para famílias com crianças especiais.", tags: ["cuidado"] },
  { texto: "Visite regularmente um idoso sem família próxima, fazendo companhia e ajudando com tarefas simples do dia a dia.", tags: ["cuidado"] },
  { texto: "Organize grupos de apoio para cuidadores de pessoas com Alzheimer.", tags: ["cuidado"] },
  { texto: "Crie programa de apadrinhamento para crianças órfãs.", tags: ["cuidado"] },
  { texto: "Ajude um vizinho carente a cuidar de seu animal de estimação, levando para passear ou ajudando com alimentação.", tags: ["cuidado"] },
  { texto: "Organize turnos de cuidado para pessoas acamadas.", tags: ["cuidado"] },
  { texto: "Crie grupos de apoio emocional para enlutados.", tags: ["cuidado"] },
  { texto: "Dedique tempo a um idoso em asilo fazendo algo prático por ele, como arrumar o quarto, ler em voz alta ou simplesmente conversar.", tags: ["cuidado"] },
  { texto: "Organize cuidados especiais para mulheres grávidas sem recursos.", tags: ["cuidado"] },
  { texto: "Reconheça e valorize o sacrifício de pessoas que serviram ao país, expressando gratidão e respeito a quem você conhece.", tags: ["cuidado"] },
  { texto: "Demonstre cuidado genuíno com alguém que sofre de dores crônicas, perguntando como está e ajudando com o que precisar.", tags: ["cuidado"] },
  { texto: "Organize rede de babás voluntárias para mães solo.", tags: ["cuidado"] },
  { texto: "Acompanhe uma pessoa a uma consulta médica ou exame, oferecendo suporte emocional e prático.", tags: ["cuidado"] },
  { texto: "Passe um tempo com uma pessoa gravemente enferma, trazendo conforto, conversas carinhosas e oração.", tags: ["cuidado"] },
  { texto: "Organize grupos de apoio para famílias de viciados.", tags: ["cuidado"] },
  { texto: "Crie programa de cuidado para pessoas com deficiências múltiplas.", tags: ["cuidado"] },
  { texto: "Ajude uma pessoa com dificuldades de locomoção com tarefas práticas, como compras, deslocamentos ou serviços domésticos.", tags: ["cuidado"] },
  { texto: "Trate com paciência e respeito pessoas com necessidades especiais, buscando entender suas particularidades.", tags: ["cuidado"] },
  { texto: "Expresse gratidão e cuidado genuíno a um profissional de saúde que você conhece, reconhecendo o peso do seu trabalho.", tags: ["cuidado"] },

  // SIMPLICIDADE (15 práticas)
  { texto: "Organize feiras de troca onde pessoas trocam objetos ao invés de comprar.", tags: ["simplicidade"] },
  { texto: "Ensine técnicas de vida minimalista para pessoas sobrecarregadas.", tags: ["simplicidade"] },
  { texto: "Crie grupos de consumo consciente e vida sustentável.", tags: ["simplicidade"] },
  { texto: "Ofereça workshops sobre organização doméstica e desapego.", tags: ["simplicidade"] },
  { texto: "Organize mutirões de doação de objetos não utilizados.", tags: ["simplicidade"] },
  { texto: "Ensine técnicas de meditação e contemplação silenciosa.", tags: ["simplicidade"] },
  { texto: "Crie hortas urbanas comunitárias para produção própria.", tags: ["simplicidade"] },
  { texto: "Ofereça cursos de artesanato com materiais reciclados.", tags: ["simplicidade"] },
  { texto: "Organize grupos de caminhada e contemplação da natureza.", tags: ["simplicidade"] },
  { texto: "Ensine técnicas de culinária simples e nutritiva.", tags: ["simplicidade"] },
  { texto: "Crie espaços de leitura ao ar livre com livros simples.", tags: ["simplicidade"] },
  { texto: "Ofereça workshops sobre economia doméstica e planejamento financeiro.", tags: ["simplicidade"] },
  { texto: "Organize encontros de música acústica e canto comunitário.", tags: ["simplicidade"] },
  { texto: "Ensine técnicas de jardinagem urbana em pequenos espaços.", tags: ["simplicidade"] },
  { texto: "Crie grupos de apoio para pessoas que querem viver com menos.", tags: ["simplicidade"] }
];