// lib/praticasData.ts

export interface Pratica {
  texto: string;
  tags: string[];
}

export const praticas: Pratica[] = [
  // JANEIRO — Recomeço & Propósito (fé, direção)
  { texto: "Escreva em um papel qual o seu principal objetivo para este ano e cole em um lugar visível.", tags: ["fé", "direção"] },
  { texto: "Separe 5 minutos para orar pedindo clareza sobre o que Deus quer para a sua vida neste ano.", tags: ["fé", "direção"] },
  { texto: "Leia uma passagem bíblica que fale sobre propósito e anote o que ela diz para você.", tags: ["fé", "direção"] },
  { texto: "Converse com alguém de confiança sobre o que você sente que Deus está chamando você a fazer.", tags: ["fé", "direção"] },
  { texto: "Descarte algo que está atrapalhando seu crescimento — um hábito, um objeto ou um compromisso desnecessário.", tags: ["fé", "direção"] },
  { texto: "Escreva três coisas que você quer que sejam diferentes na sua vida até o final do ano.", tags: ["fé", "direção"] },
  { texto: "Ore pela manhã pedindo que Deus guie seus passos antes mesmo de você começar o dia.", tags: ["fé", "direção"] },
  { texto: "Escolha uma palavra que represente o que você quer viver este ano e coloque como lembrete no celular.", tags: ["fé", "direção"] },
  { texto: "Compartilhe com um amigo ou familiar sobre um sonho que você ainda não colocou em prática.", tags: ["fé", "direção"] },
  { texto: "Escreva uma oração com suas esperanças e planos para este ano e guarde para reler depois.", tags: ["fé", "direção"] },
  { texto: "Avalie uma área da sua vida que precisa de mais direção de Deus e ore especificamente por ela.", tags: ["fé", "direção"] },
  { texto: "Leia o Salmo 1 e reflita sobre quais caminhos você está escolhendo trilhar.", tags: ["fé", "direção"] },
  { texto: "Abra mão de uma distração que tem tirado você do seu propósito — redes sociais, TV, distrações online.", tags: ["fé", "direção"] },
  { texto: "Agradeça a Deus por pelo menos três coisas boas que você viveu no ano anterior.", tags: ["fé", "direção", "gratidão"] },
  { texto: "Defina um hábito espiritual simples que você quer manter este ano — como orar ao acordar ou ler a Bíblia antes de dormir.", tags: ["fé", "direção"] },

  // FEVEREIRO — Fé & Constância (fé, constância)
  { texto: "Comprometa-se a ler a Bíblia por pelo menos 5 minutos todo dia esta semana.", tags: ["fé", "constância"] },
  { texto: "Quando bater a preguiça de orar, ore mesmo assim — mesmo que seja por apenas 2 minutos.", tags: ["fé", "constância"] },
  { texto: "Escreva em um papel: 'Mesmo sem vontade, vou...' e complete com algo que você precisa fazer pela fé.", tags: ["fé", "constância"] },
  { texto: "Retome uma prática espiritual que você abandonou e dê um primeiro passo hoje.", tags: ["fé", "constância"] },
  { texto: "Compartilhe com alguém como Deus tem sido fiel na sua vida, mesmo quando você não percebeu.", tags: ["fé", "constância"] },
  { texto: "Ore por uma pessoa que você conhece que está desanimada ou perdendo a fé.", tags: ["fé", "constância"] },
  { texto: "Marque no celular um horário fixo para orar todos os dias desta semana e cumpra.", tags: ["fé", "constância"] },
  { texto: "Fale com Deus sobre uma área da sua vida onde você está achando difícil confiar nele.", tags: ["fé", "constância"] },
  { texto: "Envie uma mensagem para alguém dizendo que você está orando por essa pessoa.", tags: ["fé", "constância"] },
  { texto: "Escreva três momentos em que Deus te foi fiel mesmo quando você duvidou.", tags: ["fé", "constância"] },
  { texto: "Quando surgir um pensamento de desânimo, substitua-o conscientemente por uma verdade bíblica.", tags: ["fé", "constância"] },
  { texto: "Escolha um versículo para memorizar esta semana e repita-o ao longo do dia.", tags: ["fé", "constância"] },
  { texto: "Ouça ou assista a um testemunho que fortaleça a sua fé.", tags: ["fé", "constância"] },
  { texto: "Ore especificamente por um projeto ou sonho que você tem deixado de lado por falta de ânimo.", tags: ["fé", "constância"] },
  { texto: "Leia Hebreus 11 e escolha um versículo sobre perseverança que fale ao seu coração hoje.", tags: ["fé", "constância"] },

  // MARÇO — Perseverança (força, constância)
  { texto: "Quando sentir vontade de desistir de algo hoje, continue por mais 5 minutos antes de parar.", tags: ["força", "constância"] },
  { texto: "Releia algo que você escreveu quando estava motivado e deixe isso te reaquecer.", tags: ["força", "constância"] },
  { texto: "Ligue para alguém que você sabe que está na luta e diga que você acredita nessa pessoa.", tags: ["força", "constância"] },
  { texto: "Escreva os motivos pelos quais você começou aquilo que está pensando em abandonar.", tags: ["força", "constância"] },
  { texto: "Ore pedindo força para este dia, especificamente para o que está sendo mais difícil.", tags: ["força", "constância"] },
  { texto: "Faça uma coisa que você tem adiado por preguiça ou cansaço — só uma.", tags: ["força", "constância"] },
  { texto: "Conte para alguém de confiança que está difícil — não carregue esse peso sozinho.", tags: ["força", "constância"] },
  { texto: "Leia Filipenses 4:13 e leve esse versículo no coração durante o dia.", tags: ["força", "constância"] },
  { texto: "Celebre uma pequena vitória de hoje, por menor que pareça.", tags: ["força", "constância"] },
  { texto: "Descanse intencionalmente hoje — cansaço não combatido vira desistência.", tags: ["força", "constância"] },
  { texto: "Ajude alguém que também está na luta — muitas vezes ajudar o outro nos dá força para continuar.", tags: ["força", "constância"] },
  { texto: "Escreva o que você acredita que virá depois desse período difícil.", tags: ["força", "constância"] },
  { texto: "Peça a um amigo que te pergunte amanhã como você está indo — crie responsabilidade mútua.", tags: ["força", "constância"] },
  { texto: "Durma mais cedo hoje. O corpo cansado dificulta a perseverança.", tags: ["força", "constância"] },
  { texto: "Agradeça a Deus por cada dia que você não desistiu até aqui.", tags: ["força", "constância", "gratidão"] },

  // ABRIL — Esperança (esperança)
  { texto: "Escreva três coisas que você ainda acredita que podem acontecer na sua vida.", tags: ["esperança"] },
  { texto: "Ore por alguém que está passando por um momento difícil, pedindo a Deus que encha essa pessoa de esperança.", tags: ["esperança"] },
  { texto: "Leia Romanos 15:13 em voz alta e receba as palavras como uma oração pessoal.", tags: ["esperança"] },
  { texto: "Compartilhe com alguém uma história de como Deus trouxe esperança em um momento que parecia sem saída.", tags: ["esperança"] },
  { texto: "Plante algo — uma semente, uma muda de planta — como símbolo de esperança e cuidado.", tags: ["esperança"] },
  { texto: "Escreva uma carta para você mesmo no futuro, expressando o que você espera que Deus faça.", tags: ["esperança"] },
  { texto: "Vá a um lugar na natureza — parque, jardim ou praça — e contemple a criação como sinal de que Deus cuida.", tags: ["esperança"] },
  { texto: "Ligue para alguém que está passando por uma fase difícil e diga que há um amanhã melhor.", tags: ["esperança"] },
  { texto: "Ouça ou cante uma música de louvor que fale de esperança.", tags: ["esperança", "alegria"] },
  { texto: "Quando o pensamento 'não vai funcionar' aparecer, substitua-o por: 'e se funcionar?'.", tags: ["esperança"] },
  { texto: "Doe um item que você não usa mais para alguém que precisa — é um ato de esperança prática.", tags: ["esperança", "amor"] },
  { texto: "Ore com uma reflexão sobre o que a ressurreição de Cristo significa concretamente para você hoje.", tags: ["esperança", "fé"] },
  { texto: "Desenhe ou escreva algo que represente o futuro que você acredita que Deus preparou para você.", tags: ["esperança"] },
  { texto: "Agradeça por uma coisa boa que você esperou e que aconteceu.", tags: ["esperança", "gratidão"] },
  { texto: "Escreva numa folha: 'Ainda espero por...' e traga isso em oração.", tags: ["esperança", "fé"] },

  // MAIO — Amor & Relações (amor)
  { texto: "Ligue ou mande mensagem para alguém que você ama e não fala há um bom tempo.", tags: ["amor"] },
  { texto: "Diga 'eu te amo' ou 'você é importante para mim' para alguém hoje.", tags: ["amor"] },
  { texto: "Faça algo sem esperar nada em troca — pague o café de alguém, segure a porta, ofereça um sorriso.", tags: ["amor"] },
  { texto: "Escreva um bilhete de agradecimento para alguém que faz parte da sua vida.", tags: ["amor", "gratidão"] },
  { texto: "Passe tempo de qualidade com uma pessoa próxima, sem celular — só presença.", tags: ["amor"] },
  { texto: "Perdoe alguém que te magoou, mesmo que seja só no seu coração, sem precisar de uma grande conversa.", tags: ["amor", "perdão"] },
  { texto: "Prepare uma refeição para alguém que está sozinho ou passando por um momento difícil.", tags: ["amor"] },
  { texto: "Pergunte a alguém próximo 'como você está de verdade?' e ouça com atenção total.", tags: ["amor"] },
  { texto: "Ore pela sua família ou pelas relações mais importantes da sua vida.", tags: ["amor", "fé"] },
  { texto: "Doe algo que outra pessoa precisa mais do que você — uma roupa, um alimento, um objeto.", tags: ["amor"] },
  { texto: "Ajude um vizinho com algo simples — carregue uma sacola, empreste algo, ajude com uma tarefa.", tags: ["amor"] },
  { texto: "Dê um abraço sincero em alguém hoje.", tags: ["amor"] },
  { texto: "Escolha não brigar por algo pequeno — pratique a paz em um relacionamento.", tags: ["amor", "paz"] },
  { texto: "Descubra como alguém da sua família está se sentindo e demonstre interesse genuíno.", tags: ["amor"] },
  { texto: "Faça uma surpresa carinhosa para alguém — pode ser uma mensagem inesperada, um mimo pequeno, ou só aparecer.", tags: ["amor"] },

  // JUNHO — Confiança (confiança)
  { texto: "Escreva uma preocupação em um papel e ore, entregando essa situação a Deus.", tags: ["confiança"] },
  { texto: "Leia Provérbios 3:5-6 e reflita sobre o que significa confiar em Deus na prática do seu dia a dia.", tags: ["confiança", "sabedoria"] },
  { texto: "Identifique algo que você está tentando controlar e decida conscientemente soltar.", tags: ["confiança"] },
  { texto: "Ore pedindo que Deus mostre o próximo passo — sem precisar ver o caminho todo.", tags: ["confiança", "fé"] },
  { texto: "Compartilhe com alguém uma situação em que você viu Deus agir quando você parou de resolver tudo sozinho.", tags: ["confiança", "fé"] },
  { texto: "Escreva uma oração de entrega sobre algo que está pesando no seu coração.", tags: ["confiança"] },
  { texto: "Quando a ansiedade bater hoje, respire fundo e repita em voz baixa: 'Deus tem o controle'.", tags: ["confiança", "paz"] },
  { texto: "Converse com alguém de confiança sobre um medo que você está carregando sozinho.", tags: ["confiança"] },
  { texto: "Ore pelo restante do ano: agradeça pelo que passou e confie o que ainda está por vir.", tags: ["confiança", "gratidão"] },
  { texto: "Leia Salmos 46:10 — 'Aquietai-vos e sabei que eu sou Deus' — e fique em silêncio por 2 minutos.", tags: ["confiança", "paz"] },
  { texto: "Identifique algo que te causa ansiedade e entregue em oração, uma coisa de cada vez.", tags: ["confiança"] },
  { texto: "Compartilhe com alguém como você tem aprendido a confiar em Deus neste ano.", tags: ["confiança", "fé"] },
  { texto: "Evite planejar em excesso hoje — confie que Deus cuidará dos detalhes.", tags: ["confiança"] },
  { texto: "Ore por alguém que está enfrentando uma situação completamente fora do seu controle.", tags: ["confiança", "fé"] },
  { texto: "Leia um testemunho de alguém que confiou em Deus em uma situação difícil e deixe isso te inspirar.", tags: ["confiança", "fé"] },

  // JULHO — Descanso & Paz (paz, serenidade)
  { texto: "Reserve 10 minutos hoje para ficar em silêncio, longe de telas e barulho.", tags: ["paz", "serenidade"] },
  { texto: "Durma mais cedo hoje ou tire uma soneca — seu descanso é sagrado.", tags: ["paz", "serenidade"] },
  { texto: "Dê uma caminhada sem destino fixo, apenas desfrutando o momento presente.", tags: ["paz", "serenidade"] },
  { texto: "Leia o Salmo 23 em voz alta devagar e receba as palavras como um presente de Deus.", tags: ["paz", "serenidade"] },
  { texto: "Desative as notificações do celular por algumas horas e respire.", tags: ["paz", "serenidade"] },
  { texto: "Ore em silêncio — sem lista de pedidos, apenas presença e descanso com Deus.", tags: ["paz", "serenidade"] },
  { texto: "Ouça uma música suave ou sons da natureza enquanto descansa conscientemente.", tags: ["paz", "serenidade"] },
  { texto: "Escreva três coisas simples pelas quais você é grato hoje.", tags: ["paz", "serenidade", "gratidão"] },
  { texto: "Saia de casa apenas para observar a natureza por alguns minutos — sem celular.", tags: ["paz", "serenidade"] },
  { texto: "Faça algo que te traz alegria sem propósito produtivo — ler por prazer, cozinhar algo gostoso.", tags: ["paz", "serenidade", "alegria"] },
  { texto: "Tire uma hora de descanso genuíno, sem culpa.", tags: ["paz", "serenidade"] },
  { texto: "Converse com Deus de forma tranquila e sem pressa — como um amigo próximo.", tags: ["paz", "serenidade"] },
  { texto: "Prepare um chá, sente-se confortavelmente e leia algo que nutre a sua alma.", tags: ["paz", "serenidade"] },
  { texto: "Escreva o que tem perturbado sua paz e ore pedindo a Deus que cuide disso.", tags: ["paz", "serenidade"] },
  { texto: "Desligue da produtividade por uma hora — a vida é mais que rendimento.", tags: ["paz", "serenidade"] },

  // AGOSTO — Sabedoria (sabedoria)
  { texto: "Antes de tomar uma decisão importante hoje, faça uma pausa e ore pedindo sabedoria.", tags: ["sabedoria", "direção"] },
  { texto: "Converse com alguém mais experiente sobre um desafio que você está enfrentando.", tags: ["sabedoria"] },
  { texto: "Leia Provérbios 1:7 e reflita sobre o que o 'temor do Senhor' significa para você.", tags: ["sabedoria", "fé"] },
  { texto: "Escreva sobre uma decisão que você precisa tomar: prós, contras e o que você sente que Deus diz.", tags: ["sabedoria", "direção"] },
  { texto: "Peça conselho para alguém de confiança antes de agir em uma situação importante.", tags: ["sabedoria"] },
  { texto: "Compartilhe com alguém mais jovem um aprendizado valioso da sua experiência de vida.", tags: ["sabedoria"] },
  { texto: "Leia um capítulo de Provérbios hoje e escolha um versículo para meditar.", tags: ["sabedoria", "fé"] },
  { texto: "Avalie um hábito que não está trazendo bons frutos e pense em como mudá-lo.", tags: ["sabedoria"] },
  { texto: "Ore especificamente por sabedoria em uma área da sua vida onde você precisa de direção.", tags: ["sabedoria", "direção"] },
  { texto: "Escreva três lições que você aprendeu no primeiro semestre deste ano.", tags: ["sabedoria", "gratidão"] },
  { texto: "Antes de responder a algo com emoção, respire e espere — a sabedoria sabe quando falar.", tags: ["sabedoria"] },
  { texto: "Reconheça e assuma um erro cometido recentemente — isso é sinal de maturidade genuína.", tags: ["sabedoria"] },
  { texto: "Leia sobre alguém da Bíblia que tomou uma decisão sábia e se inspire com esse exemplo.", tags: ["sabedoria", "fé"] },
  { texto: "Compartilhe uma palavra de sabedoria com alguém que está em dúvida sobre uma decisão.", tags: ["sabedoria"] },
  { texto: "Dedique tempo a aprender algo que vai te tornar mais capaz de servir a Deus e às pessoas.", tags: ["sabedoria", "fé"] },

  // SETEMBRO — Gratidão (gratidão)
  { texto: "Escreva 5 coisas pelas quais você é grato hoje — pequenas e grandes.", tags: ["gratidão"] },
  { texto: "Diga 'obrigado' de forma genuína e específica para alguém que fez algo bem por você.", tags: ["gratidão", "amor"] },
  { texto: "Ore começando com 5 minutos apenas de agradecimento, sem fazer nenhum pedido.", tags: ["gratidão", "fé"] },
  { texto: "Escreva uma mensagem de agradecimento para alguém que marcou a sua vida.", tags: ["gratidão", "amor"] },
  { texto: "Lembre de uma dificuldade que você passou e agradeça pelo que ela te ensinou.", tags: ["gratidão"] },
  { texto: "Faça algo especial para alguém que se dedicou por você — um abraço, uma palavra, um gesto.", tags: ["gratidão", "amor"] },
  { texto: "Compartilhe com alguém uma coisa boa que Deus fez na sua vida recentemente.", tags: ["gratidão", "fé"] },
  { texto: "Olhe ao redor da sua casa e seja grato por algo que você normalmente ignora.", tags: ["gratidão"] },
  { texto: "Leia o Salmo 100 e transforme-o em uma oração pessoal de gratidão.", tags: ["gratidão", "fé"] },
  { texto: "Escreva uma carta de gratidão para Deus — informal, como se fosse para um amigo.", tags: ["gratidão", "fé"] },
  { texto: "Fale sobre algo que aconteceu de bom esta semana com alguém próximo.", tags: ["gratidão", "amor"] },
  { texto: "Evite reclamar por um dia inteiro e substitua as queixas por agradecimento.", tags: ["gratidão"] },
  { texto: "Agradeça a alguém que serve você habitualmente — o entregador, o zelador, o caixa do mercado.", tags: ["gratidão", "amor"] },
  { texto: "Escreva sobre um relacionamento pelo qual você é especialmente grato e por quê.", tags: ["gratidão", "amor"] },
  { texto: "Compartilhe uma bênção que você recebeu com alguém que está precisando — seja de tempo, atenção ou recursos.", tags: ["gratidão", "amor"] },

  // OUTUBRO — Obediência & Direção (direção, fé)
  { texto: "Ore pedindo que Deus mostre se tem algo na sua vida que está fora do lugar.", tags: ["direção", "fé"] },
  { texto: "Leia uma passagem bíblica e pergunte: 'O que Deus está me pedindo para fazer agora?'.", tags: ["direção", "fé"] },
  { texto: "Identifique algo que Deus tem colocado no seu coração e dê um primeiro passo hoje.", tags: ["direção", "fé"] },
  { texto: "Avalie se suas prioridades de tempo refletem o que você diz ser mais importante.", tags: ["direção", "sabedoria"] },
  { texto: "Escreva o que você acredita que Deus está chamando você a fazer no restante do ano.", tags: ["direção", "fé"] },
  { texto: "Ore sobre algo que você tem adiado por medo ou insegurança.", tags: ["direção", "fé"] },
  { texto: "Converse com alguém de confiança sobre onde você sente que Deus está te guiando.", tags: ["direção", "fé"] },
  { texto: "Leia Lucas 9:23 e reflita sobre o que significa negar-se a si mesmo na sua rotina de hoje.", tags: ["direção", "fé"] },
  { texto: "Identifique uma área onde você sabe o que é certo mas tem evitado fazer — e dê um passo.", tags: ["direção", "fé"] },
  { texto: "Reveja suas metas de início de ano e pergunte se elas ainda alinham com o que Deus coloca no seu coração.", tags: ["direção", "fé"] },
  { texto: "Ore pela liderança da sua vida — família, trabalho, relacionamentos — pedindo direção.", tags: ["direção", "fé"] },
  { texto: "Reconheça se tem algo que você precisa arrumar com alguém — e dê o primeiro passo.", tags: ["direção", "amor"] },
  { texto: "Compartilhe com alguém de confiança o que você sente que Deus está falando para você nesta temporada.", tags: ["direção", "fé"] },
  { texto: "Pratique dizer 'não' a algo que não alinha com o seu propósito, sem culpa.", tags: ["direção"] },
  { texto: "Ore pedindo coragem para obedecer Deus mesmo quando não é fácil ou conveniente.", tags: ["direção", "fé"] },

  // NOVEMBRO — Força & Superação (força)
  { texto: "Ore pela manhã declarando: 'Tenho forças para este dia, em Cristo.'", tags: ["força", "fé"] },
  { texto: "Escreva três desafios que você já superou e lembre-se de que você tem capacidade.", tags: ["força"] },
  { texto: "Ligue para alguém que está com a carga pesada e ofereça um apoio concreto.", tags: ["força", "amor"] },
  { texto: "Faça alguma atividade física hoje — o corpo fortalecido ajuda a mente e a alma.", tags: ["força"] },
  { texto: "Recuse-se a ficar paralisado pelo cansaço — faça uma coisa, só uma, hoje.", tags: ["força"] },
  { texto: "Compartilhe com alguém uma situação difícil que você está enfrentando e peça oração.", tags: ["força", "fé"] },
  { texto: "Leia Isaías 40:31 e receba as palavras como promessa de Deus para este momento.", tags: ["força", "fé"] },
  { texto: "Compre um alimento ou item básico e dê a alguém que está passando por necessidade.", tags: ["força", "amor"] },
  { texto: "Ajude alguém que está sobrecarregado com uma tarefa prática — uma carona, uma ajuda com compras.", tags: ["força", "amor"] },
  { texto: "Ore por alguém que você sabe que está no limite — que Deus renove as forças dessa pessoa.", tags: ["força", "fé"] },
  { texto: "Descanse intencionalmente hoje — a força também vem do repouso bem aproveitado.", tags: ["força", "paz"] },
  { texto: "Escreva sobre um momento em que você pensou que não ia aguentar, mas aguentou.", tags: ["força"] },
  { texto: "Fale com alguém em quem você confia sobre o quanto o final do ano está pesado.", tags: ["força", "amor"] },
  { texto: "Leia sobre Elias ou Davi na Bíblia — personagens que encontraram força em Deus na exaustão.", tags: ["força", "fé"] },
  { texto: "Faça uma coisa que você estava adiando por se sentir fraco — e comemore esse passo.", tags: ["força"] },

  // DEZEMBRO — Reflexão & Deus (gratidão, paz)
  { texto: "Reserve um tempo para rever o ano: o que aconteceu de bom? O que você aprendeu?", tags: ["gratidão", "paz"] },
  { texto: "Escreva uma carta de despedida do ano, agradecendo por tudo — inclusive as dificuldades.", tags: ["gratidão", "paz"] },
  { texto: "Ore agradecendo por cada mês do ano que passou e pelo cuidado de Deus em cada período.", tags: ["gratidão", "fé"] },
  { texto: "Crie uma tradição simples de reflexão em família ou com amigos neste fim de ano.", tags: ["gratidão", "paz", "amor"] },
  { texto: "Doe algo para alguém que precisa mais do que você — roupa, comida ou seu tempo.", tags: ["gratidão", "amor"] },
  { texto: "Compartilhe com alguém o que Deus fez de especial na sua vida este ano.", tags: ["gratidão", "fé"] },
  { texto: "Escreva 12 agradecimentos — um para cada mês do ano.", tags: ["gratidão"] },
  { texto: "Ore pelo Natal de forma diferente: ao invés de pedidos, fale sobre o nascimento de Cristo e o que ele significa.", tags: ["gratidão", "fé"] },
  { texto: "Visite ou ligue para alguém que vai passar o Natal sozinho.", tags: ["gratidão", "amor"] },
  { texto: "Escreva intenções para o próximo ano, com humildade e entrega a Deus.", tags: ["gratidão", "paz"] },
  { texto: "Compartilhe uma refeição com alguém que não teria com quem comer nessa época do ano.", tags: ["gratidão", "amor"] },
  { texto: "Leia o relato do nascimento de Jesus em Lucas 2 e medite sobre ele de forma tranquila.", tags: ["gratidão", "paz", "fé"] },
  { texto: "Escolha um presente significativo para uma pessoa próxima — que diga que você pensa nela.", tags: ["gratidão", "amor"] },
  { texto: "Fique em silêncio por 10 minutos refletindo sobre quem você quer ser no próximo ano.", tags: ["gratidão", "paz"] },
  { texto: "Escreva uma oração de encerramento do ano: agradeça, perdoe, entregue e espere.", tags: ["gratidão", "paz", "fé"] },
];
