// lib/salmosData.ts

export interface Salmo {
  referencia: string;
  texto: string;
  tags: string[];
}

export const salmos: Salmo[] = [
  { referencia: "Salmos 1:1", texto: "Bem-aventurado o homem que não anda segundo o conselho dos ímpios, nem se detém no caminho dos pecadores, nem se assenta na roda dos escarnecedores;", tags: ["direção", "sabedoria", "louvor", "perdão", "constância"] },
  { referencia: "Salmos 2:1", texto: "Por que se amotinam as nações, e os povos tramam em vão?", tags: ["confiança"] },
  { referencia: "Salmos 3:1", texto: "Senhor, como se têm multiplicado os meus adversários! Muitos se levantam contra mim.", tags: ["confiança"] },
  { referencia: "Salmos 4:1", texto: "Responde-me quando eu clamar, ó Deus da minha justiça! Na angústia me deste largueza; tem misericórdia de mim e ouve a minha oração.", tags: ["misericórdia", "justiça", "oração"] },
  { referencia: "Salmos 5:1", texto: "Dá ouvidos às minhas palavras, ó Senhor; atende aos meus gemidos.", tags: ["confiança"] },
  { referencia: "Salmos 6:1", texto: "Senhor, não me repreendas na tua ira, nem me castigues no teu furor.", tags: ["confiança"] },
  { referencia: "Salmos 7:1", texto: "Senhor, Deus meu, confio, salva-me de todo o que me persegue, e livra-me;", tags: ["confiança", "proteção", "libertação"] },
  { referencia: "Salmos 8:1", texto: "Ó Senhor, Senhor nosso, quão admirável é o teu nome em toda a terra, tu que puseste a tua glória dos céus!", tags: ["confiança"] },
  { referencia: "Salmos 9:1", texto: "Eu te louvarei, Senhor, de todo o meu coração; contarei todas as tuas maravilhas.", tags: ["louvor", "oração"] },
  { referencia: "Salmos 10:1", texto: "Por que te conservas ao longe, Senhor? Por que te escondes em tempos de angústia?", tags: ["confiança"] },
  { referencia: "Salmos 11:1", texto: "No Senhor confio. Como, pois, me dizeis: Foge para o monte, como um pássaro?", tags: ["confiança"] },
  { referencia: "Salmos 12:1", texto: "Salva-nos, Senhor, pois não existe mais o piedoso; os fiéis desapareceram dentre os filhos dos homens.", tags: ["libertação"] },
  { referencia: "Salmos 13:1", texto: "Até quando, ó Senhor, te esquecerás de mim? para sempre? Até quando esconderás de mim o teu rosto?", tags: ["confiança"] },
  { referencia: "Salmos 14:1", texto: "Diz o néscio no seu coração: Não há Deus. Os homens têm-se corrompido, fazem-se abomináveis em suas obras; não há quem faça o bem.", tags: ["oração"] },
  { referencia: "Salmos 15:1", texto: "Quem, Senhor, habitará na tua tenda? quem morará no teu santo monte?", tags: ["presença"] },
  { referencia: "Salmos 16:1", texto: "Guarda-me, ó Deus, porque em ti me refugio.", tags: ["confiança", "proteção"] },
  { referencia: "Salmos 17:1", texto: "Ouve, Senhor, a justa causa; atende ao meu clamor; dá ouvidos à minha oração, que não procede de lábios enganosos.", tags: ["oração", "amor"] },
  { referencia: "Salmos 18:1", texto: "Eu te amo, ó Senhor, força minha.", tags: ["força"] },
  { referencia: "Salmos 19:1", texto: "Os céus proclamam a glória de Deus e o firmamento anuncia a obra das suas mãos.", tags: ["confiança"] },
  { referencia: "Salmos 20:1", texto: "O Senhor te ouça no dia da angústia; o nome do Deus de Jacó te proteja.", tags: ["confiança"] },
  { referencia: "Salmos 21:1", texto: "Na tua força, ó Senhor, o rei se alegra; e na tua salvação quão grandemente se regozija!", tags: ["confiança", "força", "alegria", "libertação"] },
  { referencia: "Salmos 22:1", texto: "Deus meu, Deus meu, por que me desamparaste? por que estás afastado de me auxiliar, e das palavras do meu bramido?", tags: ["confiança"] },
  { referencia: "Salmos 23:1", texto: "O Senhor é o meu pastor; nada me faltará.", tags: ["confiança", "paz", "serenidade"] },
  { referencia: "Salmos 24:1", texto: "Do Senhor é a terra e a sua plenitude; o mundo e aqueles que nele habitam.", tags: ["presença"] },
  { referencia: "Salmos 25:1", texto: "A ti, Senhor, elevo a minha alma.", tags: ["confiança"] },
  { referencia: "Salmos 26:1", texto: "Julga-me, ó Senhor, pois tenho andado na minha integridade; no Senhor tenho confiado sem vacilar.", tags: ["confiança"] },
  { referencia: "Salmos 27:1", texto: "O Senhor é a minha luz e a minha salvação; a quem temerei? O Senhor é a força da minha vida; de quem me recearei?", tags: ["confiança", "força", "libertação"] },
  { referencia: "Salmos 28:1", texto: "A ti clamo, ó Senhor; rocha minha, não emudeças para comigo; não suceda que, calando-te a meu respeito, eu me torne semelhante aos que descem à cova.", tags: ["oração"] },
  { referencia: "Salmos 29:1", texto: "Tributai ao Senhor, ó filhos dos poderosos, tributai ao Senhor glória e força.", tags: ["força"] },
  { referencia: "Salmos 30:1", texto: "Exaltar-te-ei, ó Senhor, porque tu me levantaste, e não permitiste que meus inimigos se alegrassem sobre mim.", tags: ["louvor", "alegria"] },
  { referencia: "Salmos 31:1", texto: "Em ti, Senhor, me refugio; nunca seja eu envergonhado; livra-me pela tua justiça!", tags: ["confiança", "proteção", "justiça", "libertação"] },
  { referencia: "Salmos 32:1", texto: "Bem-aventurado aquele cuja transgressão é perdoada, e cujo pecado é coberto.", tags: ["perdão"] },
  { referencia: "Salmos 33:1", texto: "Regozijai-vos no Senhor, vós justos, pois aos retos fica bem o louvor.", tags: ["alegria", "justiça"] },
  { referencia: "Salmos 34:1", texto: "Bendirei ao Senhor em todo o tempo; o seu louvor estará continuamente na minha boca.", tags: ["confiança"] },
  { referencia: "Salmos 35:1", texto: "Contende, Senhor, com aqueles que contendem comigo; combate contra os que me combatem.", tags: ["confiança"] },
  { referencia: "Salmos 36:1", texto: "A transgressão fala ao ímpio no íntimo do seu coração; não há temor de Deus perante os seus olhos.", tags: ["perdão", "oração"] },
  { referencia: "Salmos 37:1", texto: "Não te enfades por causa dos malfeitores, nem tenhas inveja dos que praticam a iniqüidade.", tags: ["perdão", "oração", "fé"] },
  { referencia: "Salmos 38:1", texto: "Ó Senhor, não me repreendas na tua ira, nem me castigues no teu furor.", tags: ["confiança"] },
  { referencia: "Salmos 39:1", texto: "Disse eu: Guardarei os meus caminhos para não pecar com a minha língua; guardarei a minha boca com uma mordaça, enquanto o ímpio estiver diante de mim.", tags: ["proteção", "direção", "presença"] },
  { referencia: "Salmos 40:1", texto: "Esperei com paciência pelo Senhor, e ele se inclinou para mim e ouviu o meu clamor.", tags: ["oração", "amor"] },
  { referencia: "Salmos 41:1", texto: "Bem-aventurado é aquele que considera o pobre; o Senhor o livrará no dia do mal.", tags: ["proteção", "libertação"] },
  { referencia: "Salmos 42:1", texto: "Como o cervo anseia pelas correntes das águas, assim a minha alma anseia por ti, ó Deus!", tags: ["confiança", "esperança"] },
  { referencia: "Salmos 43:1", texto: "Faze-me justiça, ó Deus, e pleiteia a minha causa contra uma nação ímpia; livra-me do homem fraudulento e iníquo.", tags: ["proteção", "justiça", "libertação"] },
  { referencia: "Salmos 44:1", texto: "Ó Deus, nós ouvimos com os nossos ouvidos, nossos pais nos têm contado os feitos que realizaste em seus dias, nos tempos da antigüidade.", tags: ["fé"] },
  { referencia: "Salmos 45:1", texto: "O meu coração trasborda de boas palavras; dirijo os meus versos ao rei; a minha língua é qual pena de um hábil escriba.", tags: ["oração"] },
  { referencia: "Salmos 46:1", texto: "Deus é o nosso refúgio e fortaleza, socorro bem presente na angústia.", tags: ["confiança", "proteção", "força"] },
  { referencia: "Salmos 47:1", texto: "Batei palmas, todos os povos; aclamai a Deus com voz de júbilo.", tags: ["alegria", "oração"] },
  { referencia: "Salmos 48:1", texto: "Grande é o Senhor e mui digno de ser louvado, na cidade do nosso Deus, no seu monte santo.", tags: ["louvor"] },
  { referencia: "Salmos 49:1", texto: "Ouvi isto, vós todos os povos; inclinai os ouvidos, todos os habitantes do mundo,", tags: ["presença"] },
  { referencia: "Salmos 50:1", texto: "O Poderoso, o Senhor Deus, fala e convoca a terra desde o nascer do sol até o seu ocaso.", tags: ["força"] },
  { referencia: "Salmos 51:1", texto: "Compadece-te de mim, ó Deus, segundo a tua benignidade; apaga as minhas tansgressões, segundo a multidão das tuas misericórdias.", tags: ["misericórdia"] },
  { referencia: "Salmos 52:1", texto: "Por que te glorias na malícia, ó homem poderoso? pois a bondade de Deus subsiste em todo o tempo.", tags: ["força", "misericórdia"] },
  { referencia: "Salmos 53:1", texto: "Diz o néscio no seu coração: Não há Deus. Corromperam-se e cometeram abominável iniqüidade; não há quem faça o bem.", tags: ["perdão", "oração"] },
  { referencia: "Salmos 54:1", texto: "Salva-me, ó Deus, pelo teu nome, e faze-me justiça pelo teu poder.", tags: ["força", "justiça", "libertação"] },
  { referencia: "Salmos 55:1", texto: "Dá ouvidos, ó Deus, à minha oração, e não te escondas da minha súplica.", tags: ["oração"] },
  { referencia: "Salmos 56:1", texto: "Compadece-te de mim, ó Deus, pois homens me calcam aos pés e, pelejando, me aflingem o dia todo.", tags: ["confiança"] },
  { referencia: "Salmos 57:1", texto: "Compadece-te de mim, ó Deus, compadece-te de mim, pois em ti se refugia a minha alma; à sombra das tuas asas me refugiarei, até que passem as calamidades.", tags: ["proteção"] },
  { referencia: "Salmos 58:1", texto: "Falais deveras o que é reto, vós os poderosos? Julgais retamente, ó filhos dos homens?", tags: ["força", "justiça"] },
  { referencia: "Salmos 59:1", texto: "Livra-me, Deus meu, dos meus inimigos; protege-me daqueles que se levantam contra mim.", tags: ["proteção", "libertação"] },
  { referencia: "Salmos 60:1", texto: "Ó Deus, tu nos rejeitaste, tu nos esmagaste, tu tens estado indignado; oh, restabelece-nos.", tags: ["confiança"] },
  { referencia: "Salmos 61:1", texto: "Ouve, ó Deus, o meu clamor; atende à minha oração.", tags: ["oração", "amor"] },
  { referencia: "Salmos 62:1", texto: "Somente em Deus espera silenciosa a minha alma; dele vem a minha salvação.", tags: ["paz", "confiança", "libertação", "esperança", "serenidade"] },
  { referencia: "Salmos 63:1", texto: "Ó Deus, tu és o meu Deus; ansiosamente te busco. A minha alma tem sede de ti; a minha carne te deseja muito em uma terra seca e cansada, onde não há água.", tags: ["confiança"] },
  { referencia: "Salmos 64:1", texto: "Ouve, ó Deus, a minha voz na minha queixa; preserva a minha voz na minha queixa; preserva a minha vida do horror do inimigo.", tags: ["confiança"] },
  { referencia: "Salmos 65:1", texto: "A ti, ó Deus, é devido o louvor em Sião; e a ti se pagará o voto.", tags: ["confiança"] },
  { referencia: "Salmos 66:1", texto: "Louvai a Deus com brados de júbilo, todas as terras.", tags: ["louvor", "alegria"] },
  { referencia: "Salmos 67:1", texto: "Deus se compadeça de nós e nos abençoe, e faça resplandecer o seu rosto sobre nós,", tags: ["confiança"] },
  { referencia: "Salmos 68:1", texto: "Levanta-se Deus! Sejam dispersos os seus inimigos; fujam de diante dele os que o odeiam!", tags: ["presença"] },
  { referencia: "Salmos 69:1", texto: "Salva-me, ó Deus, pois as águas me sobem até o pescoço.", tags: ["libertação"] },
  { referencia: "Salmos 70:1", texto: "Apressa-te, ó Deus, em me livrar; Senhor, apressa-te em socorrer-me.", tags: ["proteção", "libertação"] },
  { referencia: "Salmos 71:1", texto: "Em ti, Senhor, me refugio; nunca seja eu confundido.", tags: ["confiança", "proteção", "esperança"] },
  { referencia: "Salmos 72:1", texto: "Ó Deus, dá ao rei os teus juízes, e a tua justiça ao filho do rei.", tags: ["justiça"] },
  { referencia: "Salmos 73:1", texto: "Verdadeiramente bom é Deus para com Israel, para com os limpos de coração.", tags: ["oração"] },
  { referencia: "Salmos 74:1", texto: "Ó Deus, por que nos rejeitaste para sempre? Por que se acende a tua ira contra o rebanho do teu pasto?", tags: ["confiança"] },
  { referencia: "Salmos 75:1", texto: "Damos-te graças, ó Deus, damos-te graças, pois o teu nome está perto; os que invocam o teu nome anunciam as tuas maravilhas.", tags: ["gratidão", "presença"] },
  { referencia: "Salmos 76:1", texto: "Conhecido é Deus em Judá, grande é o seu nome em Israel.", tags: ["confiança"] },
  { referencia: "Salmos 77:1", texto: "Levanto a Deus a minha voz; a Deus levanto a minha voz, para que ele me ouça.", tags: ["confiança"] },
  { referencia: "Salmos 78:1", texto: "Escutai o meu ensino, povo meu; inclinai os vossos ouvidos às palavras da minha boca.", tags: ["sabedoria"] },
  { referencia: "Salmos 79:1", texto: "Ó Deus, as nações invadiram a tua herança; contaminaram o teu santo templo; reduziram Jerusalém a ruínas.", tags: ["confiança"] },
  { referencia: "Salmos 80:1", texto: "Ó pastor de Israel, dá ouvidos; tu, que guias a José como a um rebanho, que estás entronizado sobre os querubins, resplandece.", tags: ["direção"] },
  { referencia: "Salmos 81:1", texto: "Cantai alegremente a Deus, nossa fortaleza; erguei alegres vozes ao Deus de Jacó.", tags: ["força", "alegria"] },
  { referencia: "Salmos 82:1", texto: "Deus está na assembléia divina; julga no meio dos deuses:", tags: ["confiança"] },
  { referencia: "Salmos 83:1", texto: "Ó Deus, não guardes silêncio; não te cales nem fiques impassível, ó Deus.", tags: ["paz"] },
  { referencia: "Salmos 84:1", texto: "Quão amável são os teus tabernáculos, ó Senhor dos exércitos!", tags: ["confiança"] },
  { referencia: "Salmos 85:1", texto: "Mostraste favor, Senhor, à tua terra; fizeste regressar os cativos de Jacó.", tags: ["confiança"] },
  { referencia: "Salmos 86:1", texto: "Inclina, Senhor, os teus ouvidos, e ouve-me, porque sou pobre e necessitado.", tags: ["confiança"] },
  { referencia: "Salmos 87:1", texto: "O fundamento dela está nos montes santos.", tags: ["confiança"] },
  { referencia: "Salmos 88:1", texto: "Ó Senhor, Deus da minha salvação, dia e noite clamo diante de ti.", tags: ["confiança", "presença", "libertação", "oração"] },
  { referencia: "Salmos 89:1", texto: "Cantarei para sempre as benignidades do Senhor; com a minha boca proclamarei a todas as gerações a tua fidelidade.", tags: ["misericórdia", "fé", "constância"] },
  { referencia: "Salmos 90:1", texto: "Senhor, tu tens sido o nosso refúgio de geração em geração.", tags: ["confiança", "proteção"] },
  { referencia: "Salmos 91:1", texto: "Aquele que habita no esconderijo do Altíssimo, à sombra do Todo-Poderoso descansará.", tags: ["paz", "proteção", "força", "presença", "serenidade"] },
  { referencia: "Salmos 92:1", texto: "Bom é render graças ao Senhor, e cantar louvores ao teu nome, ó Altíssimo,", tags: ["gratidão", "oração"] },
  { referencia: "Salmos 93:1", texto: "O Senhor reina; está vestido de majestade. O Senhor se revestiu, cingiu-se de fortaleza; o mundo também está estabelecido, de modo que não pode ser abalado.", tags: ["força"] },
  { referencia: "Salmos 94:1", texto: "Ó Senhor, Deus da vingança, ó Deus da vingança, resplandece!", tags: ["confiança"] },
  { referencia: "Salmos 95:1", texto: "Vinde, cantemos alegremente ao Senhor, cantemos com júbilo à rocha da nossa salvação.", tags: ["confiança", "alegria", "libertação"] },
  { referencia: "Salmos 96:1", texto: "Cantai ao Senhor um cântico novo, cantai ao Senhor, todos os moradores da terra.", tags: ["louvor", "oração"] },
  { referencia: "Salmos 97:1", texto: "O Senhor reina, regozije-se a terra; alegrem-se as numerosas ilhas.", tags: ["alegria"] },
  { referencia: "Salmos 98:1", texto: "Cantai ao Senhor um cântico novo, porque ele tem feito maravilhas; a sua destra e o seu braço santo lhe alcançaram a vitória.", tags: ["força", "fé"] },
  { referencia: "Salmos 99:1", texto: "O Senhor reina, tremam os povos; ele está entronizado sobre os querubins, estremeça a terra.", tags: ["confiança"] },
  { referencia: "Salmos 100:1", texto: "Celebrai com júbilo ao Senhor, todos os habitantes da terra.", tags: ["alegria", "presença"] },
  { referencia: "Salmos 101:1", texto: "Cantarei a benignidade e o juízo; a ti, Senhor, cantarei.", tags: ["misericórdia", "justiça"] },
  { referencia: "Salmos 102:1", texto: "Ó Senhor, ouve a minha oração, e chegue a ti o meu clamor.", tags: ["oração", "amor"] },
  { referencia: "Salmos 103:1", texto: "Bendize, ó minha alma, ao Senhor, e tudo o que há em mim bendiga o seu santo nome.", tags: ["louvor"] },
  { referencia: "Salmos 104:1", texto: "Bendize, ó minha alma, ao Senhor! Senhor, Deus meu, tu és magnificentíssimo! Estás vestido de honra e de majestade,", tags: ["louvor"] },
  { referencia: "Salmos 105:1", texto: "Dai graças ao Senhor; invocai o seu nome; fazei conhecidos os seus feitos entre os povos.", tags: ["gratidão", "fé"] },
  { referencia: "Salmos 106:1", texto: "Louvai ao Senhor. Louvai ao Senhor, porque ele é bom; porque a sua benignidade dura para sempre.", tags: ["louvor", "misericórdia"] },
  { referencia: "Salmos 107:1", texto: "Dai graças ao Senhor, porque ele é bom; porque a sua benignidade dura para sempre;", tags: ["gratidão", "misericórdia"] },
  { referencia: "Salmos 108:1", texto: "Preparado está o meu coração, ó Deus; cantarei, sim, cantarei louvores, com toda a minha alma.", tags: ["oração"] },
  { referencia: "Salmos 109:1", texto: "Ó Deus do meu louvor, não te cales;", tags: ["confiança"] },
  { referencia: "Salmos 110:1", texto: "Disse o Senhor ao meu Senhor: Assenta-te à minha direita, até que eu ponha os teus inimigos por escabelo dos teus pés.", tags: ["confiança"] },
  { referencia: "Salmos 111:1", texto: "Louvai ao Senhor. De todo o coração darei graças ao Senhor, no concílio dos retos e na congregação.", tags: ["gratidão", "louvor", "justiça", "oração"] },
  { referencia: "Salmos 112:1", texto: "Louvai ao Senhor. Bem-aventurado o homem que teme ao Senhor, que em seus mandamentos tem grande prazer!", tags: ["louvor"] },
  { referencia: "Salmos 113:1", texto: "Louvai ao Senhor. Louvai, servos do Senhor, louvai o nome do Senhor.", tags: ["louvor"] },
  { referencia: "Salmos 114:1", texto: "Quando Israel saiu do Egito, e a casa de Jacó dentre um povo de língua estranha,", tags: ["confiança"] },
  { referencia: "Salmos 115:1", texto: "Não a nós, Senhor, não a nós, mas ao teu nome dá glória, por amor da tua benignidade e da tua verdade.", tags: ["misericórdia", "amor"] },
  { referencia: "Salmos 116:1", texto: "Amo ao Senhor, porque ele ouve a minha voz e a minha súplica.", tags: ["oração"] },
  { referencia: "Salmos 117:1", texto: "Louvai ao Senhor todas as nações, exaltai-o todos os povos.", tags: ["louvor"] },
  { referencia: "Salmos 118:1", texto: "Dai graças ao Senhor, porque ele é bom; porque a sua benignidade dura para sempre.", tags: ["gratidão", "misericórdia"] },
  { referencia: "Salmos 119:1", texto: "Bem-aventurados os que trilham com integridade o seu caminho, os que andam na lei do Senhor!", tags: ["direção", "constância"] },
  { referencia: "Salmos 120:1", texto: "Na minha angústia clamei ao Senhor, e ele me ouviu.", tags: ["confiança"] },
  { referencia: "Salmos 121:1", texto: "Elevo os meus olhos para os montes; de onde me vem o socorro?", tags: ["confiança", "proteção"] },
  { referencia: "Salmos 122:1", texto: "Alegrei-me quando me disseram: Vamos à casa do Senhor.", tags: ["alegria"] },
  { referencia: "Salmos 123:1", texto: "A ti levanto os meus olhos, ó tu que estás entronizado nos céus.", tags: ["confiança"] },
  { referencia: "Salmos 124:1", texto: "Se não fora o Senhor, que esteve ao nosso lado, ora diga Israel:", tags: ["confiança"] },
  { referencia: "Salmos 125:1", texto: "Aqueles que confiam no Senhor são como o monte Sião, que não pode ser abalado, mas permanece para sempre.", tags: ["confiança"] },
  { referencia: "Salmos 126:1", texto: "Quando o Senhor trouxe do cativeiro os que voltaram a Sião, éramos como os que estão sonhando.", tags: ["confiança"] },
  { referencia: "Salmos 127:1", texto: "Se o Senhor não edificar a casa, em vão trabalham os que a edificam; se o Senhor não guardar a cidade, em vão vigia a sentinela.", tags: ["proteção"] },
  { referencia: "Salmos 128:1", texto: "Bem-aventurado todo aquele que teme ao Senhor e anda nos seus caminhos.", tags: ["direção"] },
  { referencia: "Salmos 129:1", texto: "Gravemente me angustiaram desde a minha mocidade, diga agora Israel;", tags: ["confiança"] },
  { referencia: "Salmos 130:1", texto: "Das profundezas clamo a ti, ó Senhor.", tags: ["oração"] },
  { referencia: "Salmos 131:1", texto: "Senhor, o meu coração não é soberbo, nem os meus olhos são altivos; não me ocupo de assuntos grandes e maravilhosos demais para mim.", tags: ["oração", "paz", "serenidade"] },
  { referencia: "Salmos 132:1", texto: "Lembra-te, Senhor, a bem de Davi, de todas as suas aflições;", tags: ["confiança"] },
  { referencia: "Salmos 133:1", texto: "Oh! quão bom e quão suave é que os irmãos vivam em união!", tags: ["confiança"] },
  { referencia: "Salmos 134:1", texto: "Eis aqui, bendizei ao Senhor, todos vós, servos do Senhor, que de noite assistis na casa do Senhor.", tags: ["louvor"] },
  { referencia: "Salmos 135:1", texto: "Louvai ao Senhor. Louvai o nome do Senhor; louvai-o, servos do Senhor,", tags: ["louvor"] },
  { referencia: "Salmos 136:1", texto: "Dai graças ao Senhor, porque ele é bom; porque a sua benignidade dura para sempre.", tags: ["gratidão", "misericórdia"] },
  { referencia: "Salmos 137:1", texto: "Junto aos rios de Babilônia, ali nos assentamos e nos pusemos a chorar, recordando-nos de Sião.", tags: ["confiança"] },
  { referencia: "Salmos 138:1", texto: "Graças te dou de todo o meu coração; diante dos deuses a ti canto louvores.", tags: ["gratidão", "presença", "oração"] },
  { referencia: "Salmos 139:1", texto: "Senhor, tu me sondas, e me conheces.", tags: ["confiança"] },
  { referencia: "Salmos 140:1", texto: "Livra-me, ó Senhor, dos homens maus; guarda-me dos homens violentos,", tags: ["proteção", "libertação"] },
  { referencia: "Salmos 141:1", texto: "Ó Senhor, a ti clamo; dá-te pressa em me acudir! Dá ouvidos à minha voz, quando a ti clamo!", tags: ["oração"] },
  { referencia: "Salmos 142:1", texto: "Com a minha voz clamo ao Senhor; com a minha voz ao Senhor suplico.", tags: ["oração"] },
  { referencia: "Salmos 143:1", texto: "Ó Senhor, ouve a minha oração, dá ouvidos às minhas súplicas! Atende-me na tua fidelidade, e na tua retidão;", tags: ["justiça", "oração", "fé"] },
  { referencia: "Salmos 144:1", texto: "Bendito seja o Senhor, minha rocha, que adestra as minhas mãos para a peleja e os meus dedos para a guerra;", tags: ["confiança"] },
  { referencia: "Salmos 145:1", texto: "Eu te exaltarei, ó Deus, rei meu; e bendirei o teu nome pelos séculos dos séculos.", tags: ["louvor"] },
  { referencia: "Salmos 146:1", texto: "Louvai ao Senhor. Ó minha alma, louva ao Senhor.", tags: ["louvor"] },
  { referencia: "Salmos 147:1", texto: "Louvai ao Senhor; porque é bom cantar louvores ao nosso Deus; pois isso é agradável, e decoroso é o louvor.", tags: ["louvor", "oração"] },
  { referencia: "Salmos 148:1", texto: "Louvai ao Senhor! Louvai ao Senhor desde o céu, louvai-o nas alturas!", tags: ["louvor"] },
  { referencia: "Salmos 149:1", texto: "Louvai ao Senhor! Cantai ao Senhor um cântico novo, e o seu louvor na assembléia dos santos!", tags: ["louvor"] },
  { referencia: "Salmos 150:1", texto: "Louvai ao Senhor! Louvai a Deus no seu santuário; louvai-o no firmamento do seu poder!", tags: ["força", "louvor"] },
  { referencia: "Salmos 1:2", texto: "antes tem seu prazer na lei do Senhor, e na sua lei medita de dia e noite.", tags: ["confiança"] },
  { referencia: "Salmos 2:2", texto: "Os reis da terra se levantam, e os príncipes juntos conspiram contra o Senhor e contra o seu ungido, dizendo:", tags: ["confiança"] },
  { referencia: "Salmos 3:2", texto: "Muitos são os que dizem de mim: Não há socorro para ele em Deus.", tags: ["confiança", "proteção"] },
  { referencia: "Salmos 4:2", texto: "Filhos dos homens, até quando convertereis a minha glória em infâmia? Até quando amareis a vaidade e buscareis a mentira?", tags: ["confiança"] },
  { referencia: "Salmos 5:2", texto: "Atende à voz do meu clamor, Rei meu e Deus meu, pois é a ti que oro.", tags: ["oração", "amor"] },
  { referencia: "Salmos 6:2", texto: "Tem compaixão de mim, Senhor, porque sou fraco; sara-me, Senhor, porque os meus ossos estão perturbados.", tags: ["misericórdia", "cura"] },
  { referencia: "Salmos 7:2", texto: "para que ele não me arrebate, qual leão, despedaçando-me, sem que haja quem acuda.", tags: ["confiança"] },
  { referencia: "Salmos 8:2", texto: "Da boca das crianças e dos que mamam tu suscitaste força, por causa dos teus adversários para fazeres calar o inimigo e vingador.", tags: ["força", "louvor"] },
  { referencia: "Salmos 9:2", texto: "Em ti me alegrarei e exultarei; cantarei louvores ao teu nome, ó Altíssimo;", tags: ["alegria", "oração"] },
  { referencia: "Salmos 10:2", texto: "Os ímpios, na sua arrogância, perseguem furiosamente o pobre; sejam eles apanhados nas ciladas que maquinaram.", tags: ["confiança"] },
  { referencia: "Salmos 11:2", texto: "Pois eis que os ímpios armam o arco, põem a sua flecha na corda, para atirarem, às ocultas, aos retos de coração.", tags: ["justiça", "oração"] },
  { referencia: "Salmos 12:2", texto: "Cada um fala com falsidade ao seu próximo; falam com lábios lisonjeiros e coração dobre.", tags: ["oração"] },
  { referencia: "Salmos 13:2", texto: "Até quando encherei de cuidados a minha alma, tendo tristeza no meu coração cada dia? Até quando o meu inimigo se exaltará sobre mim?", tags: ["louvor", "oração"] },
  { referencia: "Salmos 14:2", texto: "O Senhor olhou do céu para os filhos dos homens, para ver se havia algum que tivesse entendimento, que buscasse a Deus.", tags: ["sabedoria"] },
  { referencia: "Salmos 15:2", texto: "Aquele que anda irrepreensivelmente e pratica a justiça, e do coração fala a verdade;", tags: ["justiça", "oração"] },
  { referencia: "Salmos 16:2", texto: "Digo ao Senhor: Tu és o meu Senhor; além de ti não tenho outro bem.", tags: ["confiança"] },
  { referencia: "Salmos 17:2", texto: "Venha de ti a minha sentença; atendam os teus olhos à eqüidade.", tags: ["confiança"] },
  { referencia: "Salmos 18:2", texto: "O Senhor é a minha rocha, a minha fortaleza e o meu libertador; o meu Deus, o meu rochedo, em quem me refúgio; o meu escudo, a força da minha salvação, e o meu alto refúgio.", tags: ["confiança", "proteção", "força", "louvor"] },
  { referencia: "Salmos 19:2", texto: "Um dia faz declaração a outro dia, e uma noite revela conhecimento a outra noite.", tags: ["sabedoria"] },
  { referencia: "Salmos 20:2", texto: "Envie-te socorro do seu santuário, e te sustenha de Sião.", tags: ["confiança", "proteção"] },
  { referencia: "Salmos 21:2", texto: "Concedeste-lhe o desejo do seu coração, e não lhe negaste a petição dos seus lábios.", tags: ["oração"] },
  { referencia: "Salmos 22:2", texto: "Deus meu, eu clamo de dia, porém tu não me ouves; também de noite, mas não acho sossego.", tags: ["paz", "oração"] },
  { referencia: "Salmos 23:2", texto: "Deitar-me faz em pastos verdejantes; guia-me mansamente a águas tranqüilas.", tags: ["paz", "direção"] },
  { referencia: "Salmos 24:2", texto: "Porque ele a fundou sobre os mares, e a firmou sobre os rios.", tags: ["confiança"] },
  { referencia: "Salmos 25:2", texto: "Deus meu, em ti confio; não seja eu envergonhado; não triunfem sobre mim os meus inimigos.", tags: ["confiança", "fé"] },
  { referencia: "Salmos 26:2", texto: "Examina-me, Senhor, e prova-me; esquadrinha o meu coração e a minha mente.", tags: ["oração"] },
  { referencia: "Salmos 27:2", texto: "Quando os malvados investiram contra mim, para comerem as minhas carnes, eles, meus adversários e meus inimigos, tropeçaram e caíram.", tags: ["confiança"] },
  { referencia: "Salmos 28:2", texto: "Ouve a voz das minhas súplicas, quando a ti clamo, quando levanto as minhas mãos para o teu santo templo.", tags: ["oração"] },
  { referencia: "Salmos 29:2", texto: "Tributai ao Senhor a glória devida ao seu nome; adorai o Senhor vestidos de trajes santos.", tags: ["louvor"] },
  { referencia: "Salmos 30:2", texto: "Ó Senhor, Deus meu, a ti clamei, e tu me curaste.", tags: ["cura"] },
  { referencia: "Salmos 31:2", texto: "Inclina para mim os teus ouvidos, livra-me depressa! Sê para mim uma rocha de refúgio, uma casa de defesa que me salve!", tags: ["confiança", "proteção", "libertação", "fé"] },
  { referencia: "Salmos 32:2", texto: "Bem-aventurado o homem a quem o Senhor não atribui a iniqüidade, e em cujo espírito não há dolo.", tags: ["perdão"] },
  { referencia: "Salmos 33:2", texto: "Louvai ao Senhor com harpa, cantai-lhe louvores com saltério de dez cordas.", tags: ["louvor", "oração"] },
  { referencia: "Salmos 34:2", texto: "No Senhor se gloria a minha alma; ouçam-no os mansos e se alegrem.", tags: ["alegria"] },
  { referencia: "Salmos 35:2", texto: "Pega do escudo e do pavês, e levanta-te em meu socorro.", tags: ["confiança", "proteção"] },
  { referencia: "Salmos 36:2", texto: "Porque em seus próprios olhos se lisonjeia, cuidando que a sua iniqüidade não será descoberta e detestada.", tags: ["perdão"] },
  { referencia: "Salmos 37:2", texto: "Pois em breve murcharão como a relva, e secarão como a erva verde.", tags: ["confiança"] },
  { referencia: "Salmos 38:2", texto: "Porque as tuas flechas se cravaram em mim, e sobre mim a tua mão pesou.", tags: ["confiança"] },
  { referencia: "Salmos 39:2", texto: "Com silêncio fiquei qual um mundo; calava-me mesmo acerca do bem; mas a minha dor se agravou.", tags: ["paz"] },
  { referencia: "Salmos 40:2", texto: "Também me tirou duma cova de destruição, dum charco de lodo; pôs os meus pés sobre uma rocha, firmou os meus passos.", tags: ["direção"] },
  { referencia: "Salmos 41:2", texto: "O Senhor o guardará, e o conservará em vida; será abençoado na terra; tu, Senhor não o entregarás à vontade dos seus inimigos.", tags: ["proteção"] },
  { referencia: "Salmos 42:2", texto: "A minha alma tem sede de Deus, do Deus vivo; quando entrarei e verei a face de Deus?", tags: ["presença"] },
  { referencia: "Salmos 43:2", texto: "Pois tu és o Deus da minha fortaleza; por que me rejeitaste? por que ando em pranto por causa da opressão do inimigo?", tags: ["força"] },
  { referencia: "Salmos 44:2", texto: "Tu expeliste as nações com a tua mão, mas a eles plantaste; afligiste os povos, mas a eles estendes-te largamente.", tags: ["confiança"] },
  { referencia: "Salmos 45:2", texto: "Tu és o mais formoso dos filhos dos homens; a graça se derramou nos teus lábios; por isso Deus te abençoou para sempre.", tags: ["amor"] },
  { referencia: "Salmos 46:2", texto: "Pelo que não temeremos, ainda que a terra se mude, e ainda que os montes se projetem para o meio dos mares;", tags: ["confiança"] },
  { referencia: "Salmos 47:2", texto: "Porque o Senhor Altíssimo é tremendo; é grande Rei sobre toda a terra.", tags: ["confiança"] },
  { referencia: "Salmos 48:2", texto: "De bela e alta situação, alegria de toda terra é o monte Sião aos lados do norte, a cidade do grande Rei.", tags: ["alegria"] },
  { referencia: "Salmos 49:2", texto: "quer humildes quer grandes, tanto ricos como pobres.", tags: ["confiança"] },
  { referencia: "Salmos 50:2", texto: "Desde Sião, a perfeição da formosura. Deus resplandece.", tags: ["fé"] },
  { referencia: "Salmos 51:2", texto: "Lava-me completamente da minha iniqüidade, e purifica-me do meu pecado.", tags: ["perdão"] },
  { referencia: "Salmos 52:2", texto: "A tua língua maquina planos de destruição, como uma navalha afiada, ó tu que usas de dolo.", tags: ["confiança"] },
  { referencia: "Salmos 53:2", texto: "Deus olha lá dos céus para os filhos dos homens, para ver se há algum que tenha entendimento, que busque a Deus.", tags: ["sabedoria"] },
  { referencia: "Salmos 54:2", texto: "Ó Deus, ouve a minha oração, dá ouvidos às palavras da minha boca.", tags: ["oração"] },
  { referencia: "Salmos 55:2", texto: "Atende-me, e ouve-me; agitado estou, e ando perplexo,", tags: ["confiança"] },
  { referencia: "Salmos 56:2", texto: "Os meus inimigos me calcam aos pés o dia todo, pois são muitos os que insolentemente pelejam contra mim.", tags: ["confiança"] },
  { referencia: "Salmos 57:2", texto: "Clamarei ao Deus altíssimo, ao Deus que por mim tudo executa.", tags: ["confiança"] },
  { referencia: "Salmos 58:2", texto: "Não, antes no coração forjais iniqüidade; sobre a terra fazeis pesar a violência das vossas mãos.", tags: ["perdão", "oração"] },
  { referencia: "Salmos 59:2", texto: "Livra-me do que praticam a iniqüidade, e salva-me dos homens sanguinários.", tags: ["proteção", "perdão", "libertação"] },
  { referencia: "Salmos 60:2", texto: "Abalaste a terra, e a fendeste; sara as suas fendas, pois ela treme.", tags: ["cura", "fé"] },
  { referencia: "Salmos 61:2", texto: "Desde a extremidade da terra clamo a ti, estando abatido o meu coração; leva-me para a rocha que é mais alta do que eu.", tags: ["oração"] },
  { referencia: "Salmos 62:2", texto: "Só ele é a minha rocha e a minha salvação; é ele a minha fortaleza; não serei grandemente abalado.", tags: ["confiança", "força", "libertação"] },
  { referencia: "Salmos 63:2", texto: "Assim no santuário te contemplo, para ver o teu poder e a tua glória.", tags: ["força"] },
  { referencia: "Salmos 64:2", texto: "Esconde-me do secreto conselho dos maus, e do ajuntamento dos que praticam a iniqüidade,", tags: ["sabedoria", "perdão", "justiça"] },
  { referencia: "Salmos 65:2", texto: "Ó tu que ouves a oração! a ti virá toda a carne.", tags: ["oração"] },
  { referencia: "Salmos 66:2", texto: "Cantai a glória do seu nome, dai glória em seu louvor.", tags: ["confiança"] },
  { referencia: "Salmos 67:2", texto: "para que se conheça na terra o seu caminho e entre todas as nações a sua salvação.", tags: ["confiança", "direção", "libertação"] },
  { referencia: "Salmos 68:2", texto: "Como é impelida a fumaça, assim tu os impeles; como a cera se derrete diante do fogo, assim pereçam os ímpios diante de Deus.", tags: ["presença"] },
  { referencia: "Salmos 69:2", texto: "Atolei-me em profundo lamaçal, onde não se pode firmar o pé; entrei na profundeza das águas, onde a corrente me submerge.", tags: ["confiança"] },
  { referencia: "Salmos 70:2", texto: "Fiquem envergonhados e confundidos os que procuram tirar-me a vida; tornem atrás e confundam-se os que me desejam o mal.", tags: ["cura"] },
  { referencia: "Salmos 71:2", texto: "Na tua justiça socorre-me e livra-me; inclina os teus ouvidos para mim, e salva-me.", tags: ["proteção", "justiça", "libertação"] },
  { referencia: "Salmos 72:2", texto: "Julgue ele o teu povo com justiça, e os teus pobres com eqüidade.", tags: ["justiça"] },
  { referencia: "Salmos 73:2", texto: "Quanto a mim, os meus pés quase resvalaram; pouco faltou para que os meus passos escorregassem.", tags: ["direção"] },
  { referencia: "Salmos 74:2", texto: "Lembra-te da tua congregação, que compraste desde a antigüidade, que remiste para ser a tribo da tua herança, e do monte Sião, em que tens habitado.", tags: ["presença"] },
  { referencia: "Salmos 75:2", texto: "Quando chegar o tempo determinado, julgarei retamente.", tags: ["confiança"] },
  { referencia: "Salmos 76:2", texto: "Em Salém está a sua tenda, e a sua morada em Sião.", tags: ["presença"] },
  { referencia: "Salmos 77:2", texto: "No dia da minha angústia busco ao Senhor; de noite a minha mão fica estendida e não se cansa; a minha alma recusa ser consolada.", tags: ["confiança"] },
  { referencia: "Salmos 78:2", texto: "Abrirei a minha boca numa parábola; proporei enigmas da antigüidade,", tags: ["oração"] },
  { referencia: "Salmos 79:2", texto: "Deram os cadáveres dos teus servos como pastos às aves dos céus, e a carne dos teus santos aos animais da terra.", tags: ["confiança"] },
  { referencia: "Salmos 80:2", texto: "Perante Efraim, Benjamim e Manassés, desperta o teu poder, e vem salvar-nos.", tags: ["força", "libertação"] },
  { referencia: "Salmos 81:2", texto: "Entoai um salmo, e fazei soar o adufe, a suave harpa e o saltério.", tags: ["fé"] },
  { referencia: "Salmos 82:2", texto: "Até quando julgareis injustamente, e tereis respeito às pessoas dos ímpios?", tags: ["confiança"] },
  { referencia: "Salmos 83:2", texto: "Pois eis que teus inimigos se alvoroçam, e os que te odeiam levantam a cabeça.", tags: ["confiança"] },
  { referencia: "Salmos 84:2", texto: "A minha alma suspira! sim, desfalece pelos átrios do Senhor; o meu coração e a minha carne clamam pelo Deus vivo.", tags: ["oração"] },
  { referencia: "Salmos 85:2", texto: "Perdoaste a iniqüidade do teu povo; cobriste todos os seus pecados.", tags: ["perdão"] },
  { referencia: "Salmos 86:2", texto: "Preserva a minha vida, pois sou piedoso; o Deus meu, salva o teu servo, que em ti confia.", tags: ["libertação"] },
  { referencia: "Salmos 87:2", texto: "O Senhor ama as portas de Sião mais do que todas as habitações de Jacó.", tags: ["presença"] },
  { referencia: "Salmos 88:2", texto: "Chegue à tua presença a minha oração, inclina os teus ouvidos ao meu clamor;", tags: ["presença", "oração", "amor"] },
  { referencia: "Salmos 89:2", texto: "Digo, pois: A tua benignidade será renovada para sempre; tu confirmarás a tua fidelidade até nos céus, dizendo:", tags: ["misericórdia", "fé"] },
  { referencia: "Salmos 90:2", texto: "Antes que nascessem os montes, ou que tivesses formado a terra e o mundo, sim, de eternidade a eternidade tu és Deus.", tags: ["confiança"] },
  { referencia: "Salmos 91:2", texto: "Direi do Senhor: Ele é o meu refúgio e a minha fortaleza, o meu Deus, em quem confio.", tags: ["confiança", "proteção", "força"] },
  { referencia: "Salmos 92:2", texto: "anunciar de manhã a tua benignidade, e à noite a tua fidelidade,", tags: ["misericórdia", "fé"] },
  { referencia: "Salmos 93:2", texto: "O teu trono está firme desde a antigüidade; desde a eternidade tu existes.", tags: ["confiança"] },
  { referencia: "Salmos 94:2", texto: "Exalta-te, ó juiz da terra! dá aos soberbos o que merecem.", tags: ["louvor"] },
  { referencia: "Salmos 95:2", texto: "Apresentemo-nos diante dele com ações de graças, e celebremo-lo com salmos de louvor.", tags: ["gratidão", "presença"] },
  { referencia: "Salmos 96:2", texto: "Cantai ao Senhor, bendizei o seu nome; anunciai de dia em dia a sua salvação.", tags: ["confiança", "louvor", "libertação"] },
  { referencia: "Salmos 97:2", texto: "Nuvens e escuridão estão ao redor dele; justiça e eqüidade são a base do seu trono.", tags: ["justiça"] },
  { referencia: "Salmos 98:2", texto: "O Senhor fez notória a sua salvação, manifestou a sua justiça perante os olhos das nações.", tags: ["confiança", "justiça", "libertação", "fé"] },
  { referencia: "Salmos 99:2", texto: "O Senhor é grande em Sião, e exaltado acima de todos os povos.", tags: ["louvor"] },
  { referencia: "Salmos 100:2", texto: "Servi ao Senhor com alegria, e apresentai-vos a ele com cântico.", tags: ["alegria"] },
  { referencia: "Salmos 101:2", texto: "Portar-me-ei sabiamente no caminho reto. Oh, quando virás ter comigo? Andarei em minha casa com integridade de coração.", tags: ["direção", "justiça", "oração"] },
  { referencia: "Salmos 102:2", texto: "Não escondas de mim o teu rosto no dia da minha angústia; inclina para mim os teus ouvidos; no dia em que eu clamar, ouve-me depressa.", tags: ["confiança"] },
  { referencia: "Salmos 103:2", texto: "Bendize, ó minha alma, ao Senhor, e não te esqueças de nenhum dos seus benefícios.", tags: ["louvor"] },
  { referencia: "Salmos 104:2", texto: "tu que te cobres de luz como de um manto, que estendes os céus como uma cortina.", tags: ["confiança"] },
  { referencia: "Salmos 105:2", texto: "Cantai-lhe, cantai-lhe louvores; falai de todas as suas maravilhas.", tags: ["oração"] },
  { referencia: "Salmos 106:2", texto: "Quem pode referir os poderosos feitos do Senhor, ou anunciar todo o seu louvor?", tags: ["força", "fé"] },
  { referencia: "Salmos 107:2", texto: "digam-no os remidos do Senhor, os quais ele remiu da mão do inimigo,", tags: ["confiança"] },
  { referencia: "Salmos 108:2", texto: "Despertai, saltério e harpa; eu mesmo despertarei a aurora.", tags: ["confiança"] },
  { referencia: "Salmos 109:2", texto: "pois a boca do ímpio e a boca fraudulenta se abrem contra mim; falam contra mim com uma língua mentirosa.", tags: ["confiança"] },
  { referencia: "Salmos 110:2", texto: "O Senhor enviará de Sião o cetro do teu poder. Domina no meio dos teus inimigos.", tags: ["força"] },
  { referencia: "Salmos 111:2", texto: "Grandes são as obras do Senhor, e para serem estudadas por todos os que nelas se comprazem.", tags: ["confiança"] },
  { referencia: "Salmos 112:2", texto: "A sua descendência será poderosa na terra; a geração dos retos será abençoada.", tags: ["força", "justiça"] },
  { referencia: "Salmos 113:2", texto: "Bendito seja o nome do Senhor, desde agora e para sempre.", tags: ["confiança"] },
  { referencia: "Salmos 114:2", texto: "Judá tornou-lhe o santuário, e Israel o seu domínio.", tags: ["confiança"] },
  { referencia: "Salmos 115:2", texto: "Por que perguntariam as nações: Onde está o seu Deus?", tags: ["confiança"] },
  { referencia: "Salmos 116:2", texto: "Porque inclina para mim o seu ouvido, invocá-lo-ei enquanto viver.", tags: ["confiança"] },
  { referencia: "Salmos 117:2", texto: "Porque a sua benignidade é grande para conosco, e a verdade do Senhor dura para sempre. Louvai ao Senhor.", tags: ["louvor", "misericórdia"] },
  { referencia: "Salmos 118:2", texto: "Diga, pois, Israel: A sua benignidade dura para sempre.", tags: ["misericórdia"] },
  { referencia: "Salmos 119:2", texto: "Bem-aventurados os que guardam os seus testemunhos, que o buscam de todo o coração,", tags: ["proteção", "oração"] },
  { referencia: "Salmos 120:2", texto: "Senhor, livra-me dos lábios mentirosos e da língua enganadora.", tags: ["proteção", "louvor", "libertação"] },
  { referencia: "Salmos 121:2", texto: "O meu socorro vem do Senhor, que fez os céus e a terra.", tags: ["confiança", "proteção", "fé"] },
  { referencia: "Salmos 122:2", texto: "Os nossos pés estão parados dentro das tuas portas, ó Jerusalém!", tags: ["confiança"] },
  { referencia: "Salmos 123:2", texto: "Eis que assim como os olhos dos servos atentam para a mão do seu senhor, e os olhos da serva para a mão de sua senhora, assim os nossos olhos atentam para o Senhor nosso Deus, até que ele se compadeça de nós.", tags: ["confiança"] },
  { referencia: "Salmos 124:2", texto: "Se não fora o Senhor, que esteve ao nosso lado, quando os homens se levantaram contra nós,", tags: ["confiança"] },
  { referencia: "Salmos 125:2", texto: "Como estão os montes ao redor de Jerusalém, assim o Senhor está ao redor do seu povo, desde agora e para sempre.", tags: ["confiança"] },
  { referencia: "Salmos 126:2", texto: "Então a nossa boca se encheu de riso e a nossa língua de cânticos. Então se dizia entre as nações: Grandes coisas fez o Senhor por eles.", tags: ["fé"] },
  { referencia: "Salmos 127:2", texto: "Inútil vos será levantar de madrugada, repousar tarde, comer o pão de dores, pois ele supre aos seus amados enquanto dormem.", tags: ["oração"] },
  { referencia: "Salmos 128:2", texto: "Pois comerás do trabalho das tuas mãos; feliz serás, e te irá bem.", tags: ["fé"] },
  { referencia: "Salmos 129:2", texto: "gravemente me angustiaram desde a minha mocidade, todavia não prevaleceram contra mim.", tags: ["confiança"] },
  { referencia: "Salmos 130:2", texto: "Senhor, escuta a minha voz; estejam os teus ouvidos atentos à voz das minhas súplicas.", tags: ["oração"] },
  { referencia: "Salmos 131:2", texto: "Pelo contrário, tenho feito acalmar e sossegar a minha alma; qual criança desmamada sobre o seio de sua mãe, qual criança desmamada está a minha alma para comigo.", tags: ["fé"] },
  { referencia: "Salmos 132:2", texto: "como jurou ao Senhor, e fez voto ao Poderoso de Jacó, dizendo:", tags: ["força", "fé"] },
  { referencia: "Salmos 133:2", texto: "É como o óleo precioso sobre a cabeça, que desceu sobre a barba, a barba de Arão, que desceu sobre a gola das suas vestes;", tags: ["confiança"] },
  { referencia: "Salmos 134:2", texto: "Erguei as mãos para o santuário, e bendizei ao Senhor.", tags: ["louvor"] },
  { referencia: "Salmos 135:2", texto: "vós que assistis na casa do Senhor, nos átrios da casa do nosso Deus.", tags: ["confiança"] },
  { referencia: "Salmos 136:2", texto: "Dai graças ao Deus dos deuses, porque a sua benignidade dura para sempre", tags: ["gratidão", "misericórdia"] },
  { referencia: "Salmos 137:2", texto: "Nos salgueiros que há no meio dela penduramos as nossas harpas,", tags: ["confiança"] },
  { referencia: "Salmos 138:2", texto: "Inclino-me para o teu santo templo, e louvo o teu nome pela tua benignidade, e pela tua fidelidade; pois engrandeceste acima de tudo o teu nome e a tua palavra.", tags: ["misericórdia", "fé"] },
  { referencia: "Salmos 139:2", texto: "Tu conheces o meu sentar e o meu levantar; de longe entendes o meu pensamento.", tags: ["confiança"] },
  { referencia: "Salmos 140:2", texto: "os quais maquinam maldades no coração; estão sempre projetando guerras.", tags: ["oração"] },
  { referencia: "Salmos 141:2", texto: "Suba a minha oração, como incenso, diante de ti, e seja o levantar das minhas mãos como o sacrifício da tarde!", tags: ["presença", "oração"] },
  { referencia: "Salmos 142:2", texto: "Derramo perante ele a minha queixa; diante dele exponho a minha tribulação.", tags: ["presença"] },
  { referencia: "Salmos 143:2", texto: "e não entres em juízo com o teu servo, porque à tua vista não se achará justo nenhum vivente.", tags: ["justiça"] },
  { referencia: "Salmos 144:2", texto: "meu refúgio e minha fortaleza, meu alto retiro e meu e meu libertador, escudo meu, em quem me refugio; ele é quem me sujeita o meu povo.", tags: ["confiança", "proteção", "força", "louvor"] },
  { referencia: "Salmos 145:2", texto: "Cada dia te bendirei, e louvarei o teu nome pelos séculos dos séculos.", tags: ["louvor"] },
  { referencia: "Salmos 146:2", texto: "Louvarei ao Senhor durante a minha vida; cantarei louvores ao meu Deus enquanto viver.", tags: ["louvor", "oração"] },
  { referencia: "Salmos 147:2", texto: "O Senhor edifica Jerusalém, congrega os dispersos de Israel;", tags: ["confiança"] },
  { referencia: "Salmos 148:2", texto: "Louvai-o, todos os seus anjos; louvai-o, todas as suas hostes!", tags: ["louvor"] },
  { referencia: "Salmos 149:2", texto: "Alegre-se Israel naquele que o fez; regozijem-se os filhos de Sião no seu Rei.", tags: ["alegria", "fé"] },
  { referencia: "Salmos 150:2", texto: "Louvai-o pelos seus atos poderosos; louvai-o conforme a excelência da sua grandeza!", tags: ["força", "louvor"] },
  { referencia: "Salmos 1:3", texto: "Pois será como a árvore plantada junto às correntes de águas, a qual dá o seu fruto na estação própria, e cuja folha não cai; e tudo quanto fizer prosperará.", tags: ["oração"] },
  { referencia: "Salmos 2:3", texto: "Rompamos as suas ataduras, e sacudamos de nós as suas cordas.", tags: ["confiança"] },
  { referencia: "Salmos 3:3", texto: "Mas tu, Senhor, és um escudo ao redor de mim, a minha glória, e aquele que exulta a minha cabeça.", tags: ["proteção"] },
  { referencia: "Salmos 4:3", texto: "Sabei que o Senhor separou para si aquele que é piedoso; o Senhor me ouve quando eu clamo a ele.", tags: ["oração"] },
  { referencia: "Salmos 5:3", texto: "Pela manhã ouves a minha voz, ó Senhor; pela manhã te apresento a minha oração, e vigio.", tags: ["oração"] },
  { referencia: "Salmos 6:3", texto: "Também a minha alma está muito perturbada; mas tu, Senhor, até quando?...", tags: ["confiança"] },
  { referencia: "Salmos 7:3", texto: "Senhor, Deus meu, se eu fiz isto, se há perversidade nas minhas mãos,", tags: ["confiança"] },
  { referencia: "Salmos 8:3", texto: "Quando contemplo os teus céus, obra dos teus dedos, a lua e as estrelas que estabeleceste,", tags: ["confiança"] },
  { referencia: "Salmos 9:3", texto: "porquanto os meus inimigos retrocedem, caem e perecem diante de ti.", tags: ["presença"] },
  { referencia: "Salmos 10:3", texto: "Pois o ímpio gloria-se do desejo do seu coração, e o que é dado à rapina despreza e maldiz o Senhor.", tags: ["oração"] },
  { referencia: "Salmos 11:3", texto: "Quando os fundamentos são destruídos, que pode fazer o justo?", tags: ["justiça"] },
  { referencia: "Salmos 12:3", texto: "Corte o Senhor todos os lábios lisonjeiros e a língua que fala soberbamente,", tags: ["confiança"] },
  { referencia: "Salmos 13:3", texto: "Considera e responde-me, ó Senhor, Deus meu; alumia os meus olhos para que eu não durma o sono da morte;", tags: ["confiança"] },
  { referencia: "Salmos 14:3", texto: "Desviaram-se todos e juntamente se fizeram imundos; não há quem faça o bem, não há sequer um.", tags: ["confiança"] },
  { referencia: "Salmos 15:3", texto: "que não difama com a sua língua, nem faz o mal ao seu próximo, nem contra ele aceita nenhuma afronta;", tags: ["confiança"] },
  { referencia: "Salmos 16:3", texto: "Quanto aos santos que estão na terra, eles são os ilustres nos quais está todo o meu prazer.", tags: ["confiança"] },
  { referencia: "Salmos 17:3", texto: "Provas-me o coração, visitas-me de noite; examinas-me e não achas iniqüidade; a minha boca não transgride.", tags: ["perdão", "oração"] },
  { referencia: "Salmos 18:3", texto: "Invoco o Senhor, que é digno de louvor, e sou salvo dos meus inimigos.", tags: ["oração"] },
  { referencia: "Salmos 19:3", texto: "Não há fala, nem palavras; não se lhes ouve a voz.", tags: ["confiança"] },
  { referencia: "Salmos 20:3", texto: "Lembre-se de todas as tuas ofertas, e aceite os teus holocaustos.", tags: ["fé"] },
  { referencia: "Salmos 21:3", texto: "Pois o proveste de bênçãos excelentes; puseste-lhe na cabeça uma coroa de ouro fino.", tags: ["confiança"] },
  { referencia: "Salmos 22:3", texto: "Contudo tu és santo, entronizado sobre os louvores de Israel.", tags: ["oração"] },
  { referencia: "Salmos 23:3", texto: "Refrigera a minha alma; guia-me nas veredas da justiça por amor do seu nome.", tags: ["direção", "justiça", "amor"] },
  { referencia: "Salmos 24:3", texto: "Quem subirá ao monte do Senhor, ou quem estará no seu lugar santo?", tags: ["confiança"] },
  { referencia: "Salmos 25:3", texto: "Não seja envergonhado nenhum dos que em ti esperam; envergonhados sejam os que sem causa procedem traiçoeiramente.", tags: ["confiança"] },
  { referencia: "Salmos 26:3", texto: "Pois a tua benignidade está diante dos meus olhos, e tenho andado na tua verdade.", tags: ["misericórdia", "presença"] },
  { referencia: "Salmos 27:3", texto: "Ainda que um exército se acampe contra mim, o meu coração não temerá; ainda que a guerra se levante contra mim, conservarei a minha confiança.", tags: ["confiança", "oração"] },
  { referencia: "Salmos 28:3", texto: "Não me arrastes juntamente com os ímpios e com os que praticam a iniqüidade, que falam de paz ao seu próximo, mas têm o mal no seu coração.", tags: ["paz", "perdão", "oração"] },
  { referencia: "Salmos 29:3", texto: "A voz do Senhor ouve-se sobre as águas; o Deus da glória troveja; o Senhor está sobre as muitas águas.", tags: ["confiança"] },
  { referencia: "Salmos 30:3", texto: "Senhor, fizeste subir a minha alma do Seol, conservaste-me a vida, dentre os que descem à cova.", tags: ["confiança"] },
  { referencia: "Salmos 31:3", texto: "Porque tu és a minha rocha e a minha fortaleza; pelo que, por amor do teu nome, guia-me e encaminha-me.", tags: ["força", "direção", "amor"] },
  { referencia: "Salmos 32:3", texto: "Enquanto guardei silêncio, consumiram-se os meus ossos pelo meu bramido durante o dia todo.", tags: ["paz"] },
  { referencia: "Salmos 33:3", texto: "Cantai-lhe um cântico novo; tocai bem e com júbilo.", tags: ["alegria"] },
  { referencia: "Salmos 34:3", texto: "Engrandeci ao Senhor comigo, e juntos exaltemos o seu nome.", tags: ["louvor"] },
  { referencia: "Salmos 35:3", texto: "Tira da lança e do dardo contra os que me perseguem. Dize à minha alma: Eu sou a tua salvação.", tags: ["confiança", "libertação"] },
  { referencia: "Salmos 36:3", texto: "As palavras da sua boca são malícia e engano; deixou de ser prudente e de fazer o bem.", tags: ["confiança"] },
  { referencia: "Salmos 37:3", texto: "Confia no Senhor e faze o bem; assim habitarás na terra, e te alimentarás em segurança.", tags: ["paz", "confiança", "presença"] },
  { referencia: "Salmos 38:3", texto: "Não há coisa sã na minha carne, por causa da tua cólera; nem há saúde nos meus ossos, por causa do meu pecado.", tags: ["perdão", "cura"] },
  { referencia: "Salmos 39:3", texto: "Escandesceu-se dentro de mim o meu coração; enquanto eu meditava acendeu-se o fogo; então com a minha língua, dizendo;", tags: ["oração"] },
  { referencia: "Salmos 40:3", texto: "Pôs na minha boca um cântico novo, um hino ao nosso Deus; muitos verão isso e temerão, e confiarão no Senhor.", tags: ["confiança"] },
  { referencia: "Salmos 41:3", texto: "O Senhor o sustentará no leito da enfermidade; tu lhe amaciarás a cama na sua doença.", tags: ["fé"] },
  { referencia: "Salmos 42:3", texto: "As minhas lágrimas têm sido o meu alimento de dia e de noite, porquanto se me diz constantemente: Onde está o teu Deus?", tags: ["confiança"] },
  { referencia: "Salmos 43:3", texto: "Envia a tua luz e a tua verdade, para que me guiem; levem-me elas ao teu santo monte, e à tua habitação.", tags: ["presença"] },
  { referencia: "Salmos 44:3", texto: "Pois não foi pela sua espada que conquistaram a terra, nem foi o seu braço que os salvou, mas a tua destra e o teu braço, e a luz do teu rosto, porquanto te agradaste deles.", tags: ["força"] },
  { referencia: "Salmos 45:3", texto: "Cinge a tua espada à coxa, ó valente, na tua glória e majestade.", tags: ["confiança"] },
  { referencia: "Salmos 46:3", texto: "ainda que as águas rujam e espumem, ainda que os montes se abalem pela sua braveza.", tags: ["confiança"] },
  { referencia: "Salmos 47:3", texto: "Ele nos sujeitou povos e nações sob os nossos pés.", tags: ["confiança"] },
  { referencia: "Salmos 48:3", texto: "Nos palácios dela Deus se fez conhecer como alto refúgio.", tags: ["confiança", "proteção", "fé"] },
  { referencia: "Salmos 49:3", texto: "A minha boca falará a sabedoria, e a meditação do meu coração será de entendimento.", tags: ["sabedoria", "oração"] },
  { referencia: "Salmos 50:3", texto: "O nosso Deus vem, e não guarda silêncio; diante dele há um fogo devorador, e grande tormenta ao seu redor.", tags: ["paz", "proteção", "louvor", "presença"] },
  { referencia: "Salmos 51:3", texto: "Pois eu conheço as minhas transgressões, e o meu pecado está sempre diante de mim.", tags: ["perdão", "presença"] },
  { referencia: "Salmos 52:3", texto: "Tu amas antes o mal do que o bem, e o mentir do que o falar a verdade.", tags: ["confiança"] },
  { referencia: "Salmos 53:3", texto: "Desviaram-se todos, e juntamente se fizeram imundos; não há quem faça o bem, não há sequer um.", tags: ["confiança"] },
  { referencia: "Salmos 54:3", texto: "Porque homens insolentes se levantam contra mim, e violentos procuram a minha vida; eles não põem a Deus diante de si.", tags: ["presença", "cura"] },
  { referencia: "Salmos 55:3", texto: "por causa do clamor do inimigo e da opressão do ímpio; pois lançam sobre mim iniqüidade, e com furor me perseguem.", tags: ["perdão", "oração", "amor"] },
  { referencia: "Salmos 56:3", texto: "No dia em que eu temer, hei de confiar em ti.", tags: ["confiança"] },
  { referencia: "Salmos 57:3", texto: "Ele do céu enviará seu auxílio , e me salvará, quando me ultrajar aquele que quer calçar-me aos pés. Deus enviará a sua misericórdia e a sua verdade.", tags: ["misericórdia", "libertação"] },
  { referencia: "Salmos 58:3", texto: "Alienam-se os ímpios desde a madre; andam errados desde que nasceram, proferindo mentiras.", tags: ["fé"] },
  { referencia: "Salmos 59:3", texto: "Pois eis que armam ciladas à minha alma; os fortes se ajuntam contra mim, não por transgressão minha nem por pecado meu, ó Senhor.", tags: ["força", "perdão"] },
  { referencia: "Salmos 60:3", texto: "Ao teu povo fizeste ver duras coisas; fizeste-nos beber o vinho de aturdimento.", tags: ["confiança"] }
];
